### ISSUE TITLE
Move plugin - namespaces and pages displays in the same way in tree-based move manager  

### ISSUE THREAD

**Issue by Digitalin** [giterlizzi/dokuwiki-template-bootstrap3#296]
### Description

Move plugin - namespaces and pages displays in the same way that makes difficult to distinguish them.

### Steps to Reproduce

1. DokuWiki Release 2017-02-19a "Frusterick Manners" - Bootstrap3 template 2016-12-12 - Move plugin 2017-01-07
2. Use the tree-based move manager of Move plugin
3. Test with Bootstrap3
4. Test with DokuWiki template

**Expected behavior:** with DokuWiki template,  there is a blue color for namespace and green for pages

[See Issue](https://github.com/michitux/dokuwiki-plugin-move/issues/96) at Move Github account

**Comment by giterlizzi** [comment]
Hi @Digitalin 
After 2 years this feature is in develop and upcoming version of template.

![immagine](https://user-images.githubusercontent.com/1824717/71536984-0c43a300-2916-11ea-8a81-551295d6beb9.png)
