### ISSUE TITLE
New version of CKG Editor does not work in Bootstrap theme

### ISSUE THREAD

**Issue by madskempel** [giterlizzi/dokuwiki-template-bootstrap3#319]
### Description

After upgrading to the newest version of CKG Editor, it only shows a white screen when you try editing a site.

### Steps to Reproduce

1. Install CKG Editor (Release version from 2017-06-24)
2. Edit a site
3. Click on CKG Edit

**Expected behavior:** 
The CKG editor should show and be able to edit the site

**Actual behavior:**
The editor windows goes white and you are not able to edit

### Versions

  * [Bootstrap3 Template] version 2016-12-12
  * [DokuWiki] Not sure how to see this
  * [Plugin] CKG Editor version from 2017-06-24
  * [Browser] Google Chrome

### Screenshots or Logs

[Paste your logs or attach the screenshot]

### Sample Page

[Paste your sample DokuWiki page]

**Comment by giterlizzi** [comment]
Hi,
The current release of template now work fine with CKGEditor Plugin.

Thanks,
Joseph
