### ISSUE TITLE
Breadcrumbs do not work

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [giterlizzi/dokuwiki-template-bootstrap3#341]
### Description

In the breadcrumb line only the latest entry is displayed. The pages which were visited before aren't indicate

### Steps to Reproduce

1. Open one wiki page
2. Open another wiki page
3. and so on...

**Expected behavior:** All visited wiki pages should be displayed in the breadcrumb area

**Actual behavior:** Only the last visited wiki page is displayed in the breadcrumb area

### Versions

  * Bootstrap3 Template: 2016-12-12
  * DokuWiki: 2017-02-19b "Frusterick Manners"
  * Browser: Firefox 57.0.4 (64-Bit), Chrome Version 63.0.3239.132 (Offizieller Build) (64-Bit)

**Comment by LotarProject** [comment]
Hi,
this is an unexpected behavior because DokuWiki store the breadcrumbs into ```$_SESSION``` array.

You can see this array in debug mode (enable ```allowdebug``` via **Configuration Setting** and visit ```/?do=debug``` page).

This is an example (see ```bc``` key):

```
$_SESSION:

Array
(
    [DW93669e0b666a85c6ffda0cf5b0a2b283] => Array
        (
            [auth] => ***
            [bc] => Array
                (
                    [start] => ::1 Wiki
                    [wiki:syntax] => Formatting Syntax
                    [playground:playground] => Playground
                )

            [translationlc] => 
        )

)
```

**Comment by Juergen-aus-Koeln** [comment]
Hi,

sorry, but in my installation the bc key is not processed:
```
$_SESSION:

Array
(
    [DWcb100c0f811c1b6d691e3e7c406b56ba] => Array
        (
            [auth] => ***
        )

)
```
I think that the misbehaviour came up since the last update of the template.

Best regards
Juergen

**Comment by LotarProject** [comment]
Seems a cookie problem.
Can you check your ``cookiedir`` configuration ?

**Comment by Juergen-aus-Koeln** [comment]
The parameter `cookiedir` is empty, and I haven't changed this configuration since I have dokuwiki in use.

**Comment by giterlizzi** [comment]
Hi, The problem still present?
