### ISSUE TITLE
Change the default Puzzle-icon for a new pluggin

### ISSUE THREAD

**Issue by sebastienPoussard** [giterlizzi/dokuwiki-template-bootstrap3#386]
Greetings, 
i'm developping a Plugin and try to make it compatible with Bootstrap3 theme.
unfortunately as exaplained here https://forum.dokuwiki.org/thread/16071 i dont know how to change the default puzzle-icon appearing when i'm creating a button.

best regards.

**Comment by giterlizzi** [comment]
Hi, the current release the template use the new DokuWiki Menu System (https://www.dokuwiki.org/devel:menus).

If the plugin use this new method, the template show automatically the icon defined in plugin, otherwise use the puzzle-icon.

At your disposal,
Joseph
