### ISSUE TITLE
translation plugin broken in bootstrap3

### ISSUE THREAD

**Issue by tmo26** [giterlizzi/dokuwiki-template-bootstrap3#389]
### Description
The translation plugin is broken in bootstrap3:
- Flags are repeated instead of being shown only once, making language text unreadable
- No action at all when clicking on a language in the pulldown menu

### Steps to reproduce
1. Install bootstrap3
2. Install translation plugin
3. configure translation plugin: show langcode, flags, names
4. Go to an arbitrary wiki page and click on the translation dropdown

**Expected behavior:**
- One flag should be shown as in screenshot below
- When clicking on a language in the translation dropdown, the page should be switched to the selected language page

**Actual behavior:**
- Flags are repeated instead of being shown only once, making language text unreadable.
- No action at all when clicking on a language in the pulldown menu, making it impossible to switch to another language via the translation dropdown.

### Versions

* [Bootstrap3 Template] 2018-02-16
* [DokuWiki] 2018-04-22a "Greebo"
* [Translation Plugin] 2018-08-07
* [Browser] FF 61.0.2 + Chrome 68.0.3440.106

### Screenshots or Logs
Translation plugin working as expected with custom template:
![grafik](https://user-images.githubusercontent.com/12309103/44006921-9bd9a368-9e8c-11e8-94da-9e4d4b35379a.png)

Translation plugin not working as expected with bootstrap3 template:
![grafik](https://user-images.githubusercontent.com/12309103/44006897-2c117d44-9e8c-11e8-994b-35785500d76a.png)

**Comment by LotarProject** [comment]
Hi @tmo26, i have replicated your configuration in testing environment and the plugin work correctly.

You can force update the plugin and the template, and try again ?

At your disposal,
Joseph

**Comment by tmo26** [comment]
After update of bootstrap3 template and re-installation of the translate plugin: No change, same as before.

**Comment by dominiquesamson** [comment]
I just hit the same problem today after upgrading to latest version of both plugins, we had to change this line to 0:
$conf['plugin']['translation']['dropdown'] = 1;

The dropdown is still there and everything seems to be displayed correctly afterwards.

**Comment by tmo26** [comment]
In which file do I find this line?

**Comment by dominiquesamson** [comment]
Yes you're right, the workaround worked for us because we only use one template, but it's still a bug.

**Comment by tmo26** [comment]
**Update**

Issue is still present with the following:

- [Bootstrap3 Template] 2019-05-22
- [DokuWiki] 2018-04-22b "Greebo"
- [Translation Plugin] 2018-08-07
- [Browser] FF 69.0.3 + Chrome 77.0.3865.120



@giterlizzi Do you have an outlook when this issue could be fixed?

**Comment by giterlizzi** [comment]
Finally fixed! :P
