### ISSUE TITLE
Hide Pagenames in Search Results

### ISSUE THREAD

**Issue by Almi14** [giterlizzi/dokuwiki-template-bootstrap3#414]
### Description

Hide Pagenames in the Search Results

### Steps to reproduce

1. Search for e.g. BlackBerry
2. Results shows first alle pagenames then all FullText Results

**Expected behavior:** Would like to hide pagenames in the Search Results

**Actual behavior:** pagenames are shown in the search Results

### Versions

* [Bootstrap3 Template] Vanilla Bootstrap Design 2018-02-16
* [DokuWiki] Release 2018-04-22 “Greebo”
* [Plugins] Addnewpage, Bootswrapper, Discussion, dw2pdf, Edittable, Encryptedpasswords, iframe, move, numbering, publish, smtp, statdisplay, wrap
* [Browser] IE 11, Firefox 60.5.0, Chrome 73

**Comment by giterlizzi** [comment]
You can replicate this behavior using https://www.dokuwiki.org/config:hidepages configuration.
