### ISSUE TITLE
Newest version unable to change theme

### ISSUE THREAD

**Issue by aubreyz** [giterlizzi/dokuwiki-template-bootstrap3#433]
### Description

Since latest update unable to change theme. Any attempt to change from whatever theme is set leads to error: 

Warning
: Cannot modify header information - headers already sent by (output started at X:\Sync\DokuWikiStick\dokuwiki\lib\tpl\bootstrap3\main.php:18) in
X:\Sync\DokuWikiStick\dokuwiki\inc\common.php
on line 2045

Changing to a different page reverts to the prior theme

Same error reported and corrected in 2016 https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/250

### Steps to reproduce

Changing theme via top toolbar

### Versions

* bootstrap3 template version: v2019-05-22
* DokuWiki version: Release 2018-04-22b "Greebo"
*  PHP version 5.6.30
* Chrome

### Screenshots or Logs

![bootbug](https://user-images.githubusercontent.com/25100168/61170319-a0d06980-a55f-11e9-906a-7480586d597c.jpg)

### Sample page or snippet

[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by aubreyz** [comment]
As a further debugging exercise I did the following confirmatory exercise using a clean install
a) Downloaded latest Dokuwiki on a stick version
b) Ran -- added username and password, cleared mapache through the firewall as usual
c) installed the bootstrap3 template
d) Went to admin and selected bootstrap as my template, press save
Then change settings for bootstrap - at this stage just select bootswatch theme and make it cosmo
ticked to show theme switcher in navbar
e) It shows up fine, but as soon as you try to change the theme using the theme switcher it crashes as above

**Comment by aubreyz** [comment]
Just giving this bug a gentle nudge as it has pretty much shut me down at this stage. Many thanks for all your excellent work on this great Theme

**Comment by dolandemort** [comment]
I can confirm that I am also getting this type of error when attempting to change themes.

```
Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\dokuwiki\inc\template.php:386) in C:\xampp\htdocs\dokuwiki\inc\common.php on line 2045
```

After choosing another theme from the dropdown in the navbar, I receive this error and a distorted page. If I then refresh the page, the theme I chose loads and the error is gone.

**Comment by dolandemort** [comment]
Have recently switched from Windows 10 to Debian and no longer get this error.

**Comment by egort** [comment]
> Just giving this bug a gentle nudge as it has pretty much shut me down at this stage. Many thanks for all your excellent work on this great Theme

It seems cookie creating order.
No issue if line 2045 
`//setcookie('DOKU_PREFS', $cookieVal, time()+365*24*3600, $cookieDir, '', ($conf['securecookie'] && is_ssl()));`
in \dokuwiki\inc\common.php will be commented out

**Comment by aubreyz** [comment]
Thanks. Not sure how to resolve this in practice - hacking common.php to resolve a critical problem in a template seems unwise.

**Comment by giterlizzi** [comment]
Hi, this problem still present in the new release of template ?

**Comment by virk** [comment]
I do not know where the problem arises from but I get these warnings, when I try to change the themes in bootstrap3-template:
"Warning: Cannot modify header information - headers already sent by (output started at /Users/Admin/Sites/veelken/lib/tpl/bootstrap3/main.php:17) in /Users/Admin/Sites/veelken/inc/common.php on line 2045"

This happens on a MacBook Pro with Catalina 10.15.4 and php 7.3.11.

**Comment by aubreyz** [comment]
Not sure why issue keeps opening and closing? Since others are still reporting the error I'm probably not going to upgrade for now though I could try on a stick/usb version when I get a chance.
