### ISSUE TITLE
How to install manually

### ISSUE THREAD

**Issue by psulat** [giterlizzi/dokuwiki-template-bootstrap3#436]
I cannot get this to install via the Dokuwiki page, including the manual page.  It always timeouts. How do I install it if I download and unzip it myself?  I put the contents in /lib/plugins/tpl/bootstrap but the template doesn't show up.  Thanks!

**Comment by LotarProject** [comment]
For manual installation, copy the content of template into ``/lib/tpl/bootstrap3`` directory.
