### ISSUE TITLE
Inconsistency between header and footer treatment of logo

### ISSUE THREAD

**Issue by leemillerau** [giterlizzi/dokuwiki-template-bootstrap3#440]
### Description

As far as I can tell the logo in the header is displayed using height = 32 and in the footer using width = 32. This leads to interesting results if displaying a user provided logo that is not square.

### Steps to reproduce

1.  Upload logo.png where height not = width with Media Manager
2. Observe different display outcome in header navbar and in footer

**Expected behavior:** [What you expected to happen]
Header and footer should display in the same way for the same logo file.

**Actual behavior:** [What actually happened]

Header and footer display logo differently

### Versions

* [Bootstrap3 Template] 2019-05-22
* [DokuWiki]2018-04-22 "Greebo" 
* [Plugins]
* [PHP]
* [Browser]Chrome
Setting: Bootswatch.com

### Screenshots or Logs

[Paste your logs or attach the screenshot]
![image](https://user-images.githubusercontent.com/56103234/66099101-f0c04900-e601-11e9-8643-8dc48b3d6d4a.png)

**Comment by giterlizzi** [comment]
Hi @leemillerau,
i have fixed this issue in last commit in development (and upcoming) release.

Joseph
