### ISSUE TITLE
Footer not always at the bottom

### ISSUE THREAD

**Issue by update-freak** [giterlizzi/dokuwiki-template-bootstrap3#441]
### Description

the black bar will not be displayed at the bottom

### Steps to reproduce

**Expected behavior:** bar is at the bottom

**Actual behavior:** bar is not at the bottom

### Versions

* Bootstrap3 Template: 2019-05-22
* DokuWiki: latest version in DSM (Synology)
* Browser: Chrome

### Screenshots or Logs

![1](https://user-images.githubusercontent.com/40196995/68074018-94824d80-fd96-11e9-9997-b8540b8c6683.png)

**Comment by phy25** [comment]
FYI https://getbootstrap.com/docs/3.4/examples/sticky-footer/

**Comment by update-freak** [comment]
Thanks! In which file from the bootstrap3 template the code has to be added?

**Comment by giterlizzi** [comment]
In last commit in develop branch i have removed the navbar style in footer. This solve (partial) the problem of sticky footer. The footer now have a clean style.


![immagine](https://user-images.githubusercontent.com/1824717/72682864-16e6f780-3ad2-11ea-981f-0ebe7a9e85af.png)

**Comment by update-freak** [comment]
ok, perfect. Thanks!

**Comment by atiq4pk** [comment]
Footer is only visible when we have checked "Display DokuWiki name, logo and tagline on footer" in configuration, otherwise footer is not visible. Is that a new change or some bug?

**Comment by giterlizzi** [comment]
This is the condition for display the footer:

https://github.com/giterlizzi/dokuwiki-template-bootstrap3/blob/3c376319dce87db755641aa178bf9d598a6b1184/tpl/footer.php#L28

**Comment by atiq4pk** [comment]
Thanks for your message. After your message, I feel, I have not asked in a good way.
In a footer; license is visible as it is enable and badges are not visible as it is not enable.
If "footer" page exist but wiki info is not enable then "footer" page doesn't included in footer.
But if I enable the wiki info then footer appears with wiki info and "footer" page. 
So, this is a case, which was not like in previous version of template.
