### ISSUE TITLE
Removal of Fontawesome broke Bootswrapper plugin icons 

### ISSUE THREAD

**Issue by TrapSpace** [giterlizzi/dokuwiki-template-bootstrap3#442]
### Description

With the removal of Fontawesome in the develop branch, this broke the icons in your Bootswrapper plugin. Since I believe they use Fontawesome form this template. 

### Steps to reproduce
1. Install this template from the develop branch
2. Install Bootswrapper plugin 
3. Add a Callout component with icon=true 
4. You see the Callout component rendered but there is no icon shown

**Expected behavior:** 
See an icon in the Callout component

**Actual behavior:** 
No icon in the Callout component
### Versions

* [Bootstrap3 Template] latest in Develop branch 
* [DokuWiki] Greebo

**Comment by giterlizzi** [comment]
Hi @TrapSpace
I have plan to switch to inline SVG icons or force "Icons" plugin dependency for Bootstrap Wrapper Plugin.

I suggest this workaround,

- install or upgrade https://www.dokuwiki.org/plugin:icons
- enable `icons>loadFontAwesome` option

Joseph

giterlizzi/dokuwiki-plugin-bootswrapper#107

**Comment by TrapSpace** [comment]
Hi @giterlizzi 

Thanks for your quick reply and the workaround. I look forward to your next updates. 

Cheers

**Comment by intervisionlord** [comment]
Sad, but this workaround does not work with some elements of wrapper (e.g. buttons).
There is no way to make a button with FA icon and text inside it, because icon placed behind button even if the icon code paced inside button container...

**Comment by giterlizzi** [comment]
In last commit in develop branch, i have re-added the support for FontAwesome4 via Iconify API.

**Comment by intervisionlord** [comment]
Thank you for your reply. I'll try to check it ASAP.
