### ISSUE TITLE
Invalid foreach in menu-tools.php

### ISSUE THREAD

**Issue by unixsheikh** [giterlizzi/dokuwiki-template-bootstrap3#444]
### Description

During an installation and setup of the latest version of Dokuwiki today, I discovered an error in the Tools menu item. See attached screenshot.

I'm not familiar with what goes into the Tools Menu, but removing the foreach of course solves the problem, but I don't know if anything that should be there goes missing.

### Versions

* 2019-05-22
* Release 2018-04-22b "Greebo"

### Screenshots or Logs

![invalid-foreach](https://user-images.githubusercontent.com/15728070/68826729-69a1ce80-069f-11ea-91d9-2d5d1fcf5dc3.png)

**Comment by giterlizzi** [comment]
Hi @unixsheikh,
Fixed this issue in master and develop release!

Thanks!
Joseph
