### ISSUE TITLE
Allowing for logos with larger heights

### ISSUE THREAD

**Issue by trinh** [giterlizzi/dokuwiki-template-bootstrap3#445]
**Is your feature request related to a problem? Please describe.**

I've been trying to insert a 171px x 60px logo into the images/logo.png location. This is larger than the 32px allowance that seems to be embedded into the template. I tried to modify line 32 of navbar.php with: 

`$logo_size = 'height="60"';`

but this doesn't seem to solve the issue, which is that the image is not centred on the top navbar.

![Screen Shot 2019-11-17 at 21 38 23](https://user-images.githubusercontent.com/4688030/69014661-892d4580-0984-11ea-965d-1045d49f58de.png)

I have tried to play with the navbar.php snippet

```
tpl_link(
                    $home_link,
                    '<img src="'.$logo.'" alt="'.$title.'" class="pull-left'.(($tagline) ? ' dw-logo-tagline' : '').'" id="dw__logo" '.$logo_size.' /> 
                    <span id="dw__title" '.($tagline ? 'style="margin-top:-5px"': '').'>'. $title . $tagline .'</span>',
                    'accesskey="h" title="[H]" class="navbar-brand"'
                );
```

but to be honest I do not understand what this section of code is doing.

**Describe the solution you'd like**

A simple code snippet that would centre the logos properly.

**Describe alternatives you've considered**

Anything helpful would be great!

**Comment by giterlizzi** [comment]
Hi,
in develop branch i have added the support of large logo (width > 32px).

Thanks for you good idea ;)

Joseph

**Comment by giterlizzi** [comment]
Header:

![immagine](https://user-images.githubusercontent.com/1824717/72683052-439c0e80-3ad4-11ea-803f-cac0fe571cf3.png)

Footer:

![immagine](https://user-images.githubusercontent.com/1824717/72683040-29fac700-3ad4-11ea-8c41-57ab20c85c07.png)

**Comment by ThSGM** [comment]
Hi!

I tried to download the development branch. Again, I used a logo with a larger size and modified line 46 to be: 
```
if ($tagline) {
                    $logo_size = 'height="60"  style="margin-top:-5px"';
                }
```

instead of say, height = "32". 

Can you walk me through how you managed to get the logo working? Is the newer developmental version supposed to automatically adjust based on the detected logo.png size or do we need to somehow configure it?
