### ISSUE TITLE
Images always aligned to left side

### ISSUE THREAD

**Issue by intervisionlord** [giterlizzi/dokuwiki-template-bootstrap3#451]
### Description
All alignment syntax ignored, all images aligned to left.
[Description of the bug or feature]

### Steps to reproduce

1. Include image in dokuwiki page
2. try to use native alignment syntax as described at https://www.dokuwiki.org/images
```
{{ wiki:dokuwiki-128.png}}
{{wiki:dokuwiki-128.png }}
{{ wiki:dokuwiki-128.png }}
```
3. All images will be aligned to left

**Expected behavior:** 
Various alignments expected

**Comment by giterlizzi** [comment]
Hi,
can you specify the DokuWiki and Template version ? You see any errors in js console or Apache error_logs ?

This syntax work fine with "stable", "previous" and "develop" versions of template.

Regards,
Joseph

**Comment by intervisionlord** [comment]
Hi,
the Dokuwiki version is "Release 2018-04-22b "Greebo"
the template version is "v2019-05-22 (develop/20200115)"

There are no errors in web-server's logs
and no errors in browser's console except this:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL ресурса: https://SITEMANE/lib/plugins/flowcharts/mermaid.min.js
URL карты кода: mermaid.min.js.map
```
But this error refers on other plugin (flowchart)

**Comment by intervisionlord** [comment]
Also i have this problem on all instances of dokuwiki+bootstrap
e.g. this is a copypaste part of page from official DW FAQ
![Imgur](https://i.imgur.com/AHFtT2P.png)

**Comment by intervisionlord** [comment]
seems i found what cause this problem - the lightbox plugin. Sorry )
