### ISSUE TITLE
Bootstrap3  Admin dropdown does not work (Torso and Wrench on upper right).

### ISSUE THREAD

**Issue by rgleason** [giterlizzi/dokuwiki-template-bootstrap3#452]
### Description

When current Bootstrap3 template is enabled the upper right Admin dropdowns (wrench and torso) do not drop down as is normal.

### Steps to reproduce

1. Use bootstrap3 template
2. Login
3. Admin dropdown access is prevented (Torso and Wrench icons do not drop down.

**Expected behavior:** [What you expected to happen]
3.  Upper right Admin  - Torso and Wrench icons should drop down and allow selection.

**Actual behavior:** They don't dropdown.
When I use dokuwiki template, the admin functions are all available, no problem.

### Versions Current.

* [Bootstrap3 Template]  Most current
* [DokuWiki]  Most Current
* [Plugins] All most current  acl, plain auth, backup tool, ckgedit, captcha, config, dw2pdf, dwedit, epub, extension, gallery, indexmenu, info, move, multiorphan, popularity, revert, safefnrecode, searchindex, dokuwiki upgrade, user and wrap plugins.  
* [PHP]   I will let you know  phpinfo.php would not run forbidden.
* [Browser]  Firefox, chrome, edge

### Screenshots or Logs
None.  Will try to find the error.log, don't seem to find it right now.
[Paste your logs or attach the screenshot]

### Sample page or snippet
None.
[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by rgleason** [comment]
When I switched from template: dokuwiki  to bootstrap3 this appeared as messages
Stylesheet ../dokuwiki/css/_search.css not found, using ../dokuwiki/css/_search.less instead. Please contact developer of "bootstrap3" template.
Stylesheet ../dokuwiki/css/_admin.css not found, using ../dokuwiki/css/_admin.less instead. Please contact developer of "bootstrap3" template.

The Debug.log was totally clear nothing to report, until I switched to bootstrap3
See the attached please.  Then when I changed conf/local.php back to use the dokuwiki template the errors stopped, you can see that in debug.log

Also see the attached screenshot.
Let me know when this is fixed please.

![Screenshot (461)](https://user-images.githubusercontent.com/2363959/72688772-84962200-3ad8-11ea-9a2b-cda711309682.png)
[debug.log.txt](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/files/4083621/debug.log.txt)

**Comment by rgleason** [comment]
The PHP version is 7.3.6
![today](https://user-images.githubusercontent.com/2363959/72692900-66421d80-3afc-11ea-8de3-03e582f99157.PNG)

**Comment by giterlizzi** [comment]
Seems you have a recent DokuWiki version with old template.
The stable DokuWiki version have switched some "core" styles from css to Less.

You can upgrade the template or edit manually the style.ini file in template directory, from:

```
[stylesheets]
; DokuWiki core styles
[...]
css/core/_search.less          = screen
[...]
```

to:
```
[stylesheets]
; DokuWiki core styles
[...]
css/core/_search.css          = screen
```

**Comment by rgleason** [comment]
I am confused. I have updated everthing, disabled, uninstalled and reinstalled most plugins. Also my version of dokuwiki is current.  What is the "old" template?  Is it something in dokuwiki?  or is the siimply the dokuwikii template and the bootstrap template?

How do I really fix this?  .... upgrade the template?  I thought I had done so, several times.

**Comment by rgleason** [comment]
I just updated to the link you provided in the update note.  5-22-19.
I don't know why it went back to previous version as I had updated it.

I find these notes at the bottom of config now. Are these errors?
I don't find the
$conf['tpl']['bootstrap3']['pageToolsAnimation'] | No setting metadata
setting in config, for example.

How do I fix this?   Remove a line from the config file perhaps?



```
$conf['plugin']['ckgedit']['groups'] | No setting metadata.
$conf['plugin']['ckgedit']['no_symlinks'] | No setting metadata.
$conf['plugin']['move']['allowrename'] | No setting metadata.
$conf['plugin']['siteexport']['debugFile'] | No setting metadata.
$conf['plugin']['siteexport']['debugLevel'] | No setting metadata.
$conf['plugin']['siteexport']['defaultAuthenticationUser'] | No setting metadata.
$conf['plugin']['siteexport']['depth'] | No setting metadata.
$conf['plugin']['siteexport']['exclude'] | No setting metadata.
$conf['plugin']['siteexport']['ignoreAJAXError'] | No setting metadata.
$conf['plugin']['siteexport']['max_execution_time'] | No setting metadata.
$conf['plugin']['siteexport']['zipfilename'] | No setting metadata.
$conf['tpl']['bootstrap3']['pageToolsAnimation'] | No setting metadata


```

**Comment by giterlizzi** [comment]
Perfect!

You can remove ``pageToolsAnimation`` option (is obsolete).

**Comment by rgleason** [comment]
I think I understand now. I should remove that option from the config flie.  Thanks very much.

**Comment by rgleason** [comment]
Now, it has gone back to this problem again.
https://github.com/giterlizzi/dokuwiki-template-bootstrap3/issues/447

I have just given up for the time being and set the template back to dokuwiki.
