### ISSUE TITLE
Question: Replacement of dokuwiki icon with 64x64 opencpn icon -> Problems

### ISSUE THREAD

**Issue by rgleason** [giterlizzi/dokuwiki-template-bootstrap3#453]
Would doing this cause problems when using bootstrap3 template causing disappearance of one of two editor icons again?  I have had to go back to template dokuwiki due to the this happening again.

**Comment by rgleason** [comment]
Yes, thankyou.  Do you know if that would be a factor in the problem that one of our editor icons gets written over or seems to disappear?

I may have to start turning off certain plugins again, testing?

**Comment by giterlizzi** [comment]
This is the correct procedure for change the DokuWiki logo:
- https://www.dokuwiki.org/template:dokuwiki#changing_the_logo
- https://www.dokuwiki.org/template:bootstrap3:customizations#change_the_logo_and_favicon

Please attach a screenshot.
