### ISSUE TITLE
Bootstrap3 template causes Opencpn wiki to loose one of the two editors in the toolbar

### ISSUE THREAD

**Issue by rgleason** [giterlizzi/dokuwiki-template-bootstrap3#454]
### Description

Bootstrap3 template causes Opencpn wiki to loose one of the two installed editors in the toolbar.
Two conditions shown, one using dokuwiki template and the other using bootstrap template

### Steps to reproduce
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn
1. Just change the template from dokuwiki to bootstrap3
2. We are using indexmenu and sidebar

**Expected behavior:** [What you expected to happen]
Bootstrap should show both editors separately in the toolbar

**Actual behavior:** [What actually happened]

One of the editors disappears.

### Versions

* [Bootstrap3 Template]  - most current
* [DokuWiki] - most current
* [Plugins] - all updated and previously listed in similar Issue reported earlier.
* [PHP]  7.3.5 I think, (See previous issue.)
* [Browser]  Firefox, Edge, Chrome

### Screenshots or Logs
DW Edit  and CkgEdit have separate icons with Dokuwiki template
![Screenshot (514)](https://user-images.githubusercontent.com/2363959/73876188-93910a00-4824-11ea-823d-1076f987e9f9.png)

Dokuwikit Template - CkgEdit Editor
![Screenshot (514)](https://user-images.githubusercontent.com/2363959/73876280-ba4f4080-4824-11ea-9a21-da0f645ecf41.png)

Dokuwiki Template - DWedit
![Screenshot (515)](https://user-images.githubusercontent.com/2363959/73876345-d8b53c00-4824-11ea-98e6-ffce2a1da9ac.png)

Bootstrap3 Template - Showing one Editor at the top of the vertical toolbar
![Screenshot (508)](https://user-images.githubusercontent.com/2363959/73876461-069a8080-4825-11ea-82ef-3a470e67d458.png)

Bootstrap3 Template loads DWedit after clicking on the Edit Icon
Button for Ckg Edit is at the bottom.
![Screenshot (507)](https://user-images.githubusercontent.com/2363959/73876518-1fa33180-4825-11ea-9bae-1f7ea5a2b706.png)

Bootstrap3 Template when the bottom Ckg Edit Button is clicked this editor is not available either.
The screen goes back to this and Ckg Edit is not made available!
![Screenshot (508)](https://user-images.githubusercontent.com/2363959/73876753-83c5f580-4825-11ea-8a76-1d1a7592365b.png)

So there are two problems:
1. Vertical Toolbar: the first editor is DWedit, but CkgEdit is not available.
2. In DWedit mode the bottom icon to CkgEdit does not work.
These work properly in Dokuwiki Template, thus bootstrap3 is doing something to prevent CkgEdit from showing properly or being activated.

**Comment by rgleason** [comment]
Perhaps I should just go back to dokuwiki-template-bootstrap3-2016-12-12.zip which works, I believe

**Comment by giterlizzi** [comment]
Hi,
the previous version of template use the different and legacy menu system. The actual version use the new menu system (same as DokuWiki template but with little bit differences for optimize the performance).
Previously i have found a bug in MenuItem implementation in DWEdit plugin (https://forum.dokuwiki.org/post/68091). The affected version is in OpenCPN Wiki (https://opencpn.org/wiki/dokuwiki/lib/plugins/dwedit/plugin.info.txt --> 2019-04-14). 

Can you update your DWEdit plugin to 2020-01-11 ?

Joseph

**Comment by rgleason** [comment]
Beautiful. Updating works now.  How did it get reverted back, I wonder?
There was no update notice on dwedit, so I guess it is not a full new version.
I will have to keep this in mind!

So sorry to bother you again about this. Thanks.
![Screenshot (516)](https://user-images.githubusercontent.com/2363959/73903068-edfe8a80-4865-11ea-8367-52fe9ac66ace.png)

Closing

**Comment by giterlizzi** [comment]
Now the Dwedit plugin release date is updated on DokuWiki.org site.

Regards
Joseph

**Comment by rgleason** [comment]
Thank you!
