### ISSUE TITLE
Sidebar confusion

### ISSUE THREAD

**Issue by ThomasMcA** [giterlizzi/dokuwiki-template-bootstrap3#455]
**Is your feature request related to a problem? Please describe.**
Usage of the sidebars is confusing.

**Describe the solution you'd like**
- The Config page says the right sidebar can only be used when the left sidebar is enabled. Why must I have both?
- OK, fine. I enabled the right sidebar, saved the config, and nothing changed.
- So I spent hours testing and researching. Wait! There's an entire page of "hooks" that let me customize the template? I've been using (and tweaking) this template for months, and I never knew those hooks existed.
- So the "hooks" page made me realize that I have to create the rightsidebar page. So I did, and now I have an empty right sidebar. Ugh. Shouldn't there be tools that add content to the right sidebar?

Suggestion 1: improve the documentation.

Suggestion 2: The Config page should look for required objects, and prompt when they don't exist. For example, after enabling the right sidebar, saving the Config page should generate a warning similar to this: "You have enabled the right sidebar, but the :rightsidebar page does not yet exist. You must manually create the :rightsidebar page before it will appear in your wiki."

**Describe alternatives you've considered**
Perhaps not using sidebars.

**Comment by aubreyz** [comment]
a) The documentation seems reasonable to me. 
b) Much of the nuts and bolts of this this is part of dokuwiki documentation (how sidebar pages are inherited and so on)

**Comment by giterlizzi** [comment]
Hi,
thanks for using my template.

> The Config page says the right sidebar can only be used when the left sidebar is enabled. Why must I have both?

If you want the default DokuWiki sidebar on right side use `sidebarPosition=right` (see `rightSidebar` config description).

> So the "hooks" page made me realize that I have to create the rightsidebar page. So I did, and now I have an empty right sidebar. Ugh. Shouldn't there be tools that add content to the right sidebar?

All "hooks" are simple DokuWiki pages and the tool to add the content in hook is DokuWiki editor page

> Suggestion 1: improve the documentation.

https://www.dokuwiki.org/template:bootstrap3:hooks this page display all DokuWiki and Template hooks

> Suggestion 2: The Config page should look for required objects, and prompt when they don't exist. For example, after enabling the right sidebar, saving the Config page should generate a warning similar to this: "You have enabled the right sidebar, but the :rightsidebar page does not yet exist. You must manually create the :rightsidebar page before it will appear in your wiki."

In this way this warning will be visible to every user and could cause confusion

At your disposal,
Joseph
