### ISSUE TITLE
Responsive TOC breaks layout

### ISSUE THREAD

**Issue by ThomasMcA** [giterlizzi/dokuwiki-template-bootstrap3#456]
### Description

The TOC creates a blank space at the top of the page.

### Steps to reproduce

TOC Settings
* tpl»bootstrap3»tocAffix - on
* tpl»bootstrap3»tocCollapseSubSections - on
* tpl»bootstrap3»tocCollapseOnScroll - off
* tpl»bootstrap3»tocCollapsed - off
* tpl»bootstrap3»tocLayout - default

After scrolling down the page so that the TOC adjusts its location, the problem goes away.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

* [Bootstrap3 Template]
  * develop/20200205
* [DokuWiki]
  * latest stable
* [Plugins]
  * lots and lots
* [PHP]
  * 7.2.24
* [Browser]
  * Both Opera and Chrome in 64bit Lubuntu

### Screenshots or Logs

![TOC](https://user-images.githubusercontent.com/1448396/74106321-de1bca80-4b33-11ea-8a7b-7939b198d6a7.png)

**Comment by giterlizzi** [comment]
Hi,
Seems and incompatibility with BlogLiks plugins, because i have found the cause in this CSS rule "div.dokuwiki #plugin_bloglinks__links" (clear:both).

Add this simple fix in your ``<dokuwiki_directory>/conf/userall.css`` and purge DW CSS cache:
```.css
div.dokuwiki #plugin_bloglinks__links {
  clear: none !important;
}
```

Joseph

**Comment by ThomasMcA** [comment]
That fixes it.

Thank you.
