### ISSUE TITLE
JQuery errors

### ISSUE THREAD

**Issue by ThomasMcA** [giterlizzi/dokuwiki-template-bootstrap3#457]
### Description

As soon as I open the debugger console, errors appear.

### Steps to reproduce

1. I connected to my website.
2. Open the debugger console

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

* [Bootstrap3 Template]
  * develop/20200205
* [DokuWiki]
  * latest stable
* [Plugins]
  * lots and lots
* [PHP]
  * 7.2.24
* [Browser]
  * Both Opera and Chrome in 64bit Lubuntu

### Screenshots or Logs

![jquery_error](https://user-images.githubusercontent.com/1448396/74107500-d9a8df00-4b3e-11ea-8198-2c026e6ed13d.png)

**Comment by giterlizzi** [comment]
Hi,
seems the JS problem is caused by Iframe Plugin.

**Comment by ThomasMcA** [comment]
Yes, that was the issue. It seems odd that a plugin that is installed, but not actively used, would cause errors like that. Even disabling it did not fix the issue - it had to be uninstalled.

Thanks for a great template!

Any idea when the BS4 version might be available?
