### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by Miro-Collas** [giterlizzi/dokuwiki-template-bootstrap3#458]
### Description
Since the release on 2019-05-22, bootstrap 3 template is spamming server logs with the following:

```
2020/02/12 06:33:45 [error] 14057#14057: *7086407 FastCGI sent in stderr: "PHP message: PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/wiki/public_html/lib/tpl/bootstrap3/main.php:17) in /home/wiki/public_html/inc/co
mmon.php on line 2045" while reading upstream, client: 162.158.106.68, server: wiki.firestormviewer.org, request: "GET /login_fail_without_cache_clear?bootswatch-theme=solar HTTP/1.1", upstream: "fastcgi://unix:/var/sock/php-fpm/firestormwiki.sock:", host: "wiki.firestor
mviewer.org"
```
This did not occur with the previous release.
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

* [Bootstrap3 Template] 2019-05-22
* [DokuWiki] Release 2018-04-22b "Greebo"
* [Plugins]
* [PHP] 7.2
* [Browser]

### Screenshots or Logs

[Paste your logs or attach the screenshot]

### Sample page or snippet

[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by giterlizzi** [comment]
Hi, this problem still present in the new release of template ?

**Comment by Miro-Collas** [comment]
Yes, sorry.

`2020/04/08 01:54:56 [error] 11128#11128: *35401627 FastCGI sent in stderr: "PHP message: PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/fswiki/public_html/lib/tpl/bootstrap3/main.php:17) in /home/fswiki/public_html/inc/common.php on line 2045" while reading upstream, client: 172.69.68.195, server: wiki.firestormviewer.org, request: "GET /fs_area_search?bootswatch-theme=slate HTTP/1.1", upstream: "fastcgi://unix:/var/sock/php-fpm/firestormwiki.sock:", host: "wiki.firestormviewer.org"`

**Comment by Erreur32** [comment]
Yes i can confirm is still present in the new release!
