### ISSUE TITLE
Missing Header Icons

### ISSUE THREAD

**Issue by PixiBixi** [giterlizzi/dokuwiki-template-bootstrap3#463]
### Description

Missing icons on all webpages

**Expected behavior:** [What you expected to happen]

Showing icons

**Actual behavior:** [What actually happened]

Missing icons:

![image](https://user-images.githubusercontent.com/2496705/78519679-7052ee80-77c4-11ea-90ce-021c9bd62c50.png)

### Versions

* [Bootstrap3 Template] : Template v2020-04-04 (hotfix/20200405)
* [DokuWiki] :  Release 2018-04-22b "Greebo"
* [Plugins] : Few
* [PHP] : 7.3.16
* [Browser] : Chrome

I'm using the bitnami image for Docker

### Screenshots or Logs

```
[Mon Apr 06 02:59:13.765357 2020] [php7:error] [pid 49] [client 172.19.0.10:59718] PHP Fatal error:  Uncaught Error: Call to a member function str() on null in /bitnami/dokuwiki/lib/tpl/bootstrap3/iconify.php:34\nStack trace:\n#0 {main}\n  thrown in /bitnami/dokuwiki/lib/tpl/bootstrap3/iconify.php on line 34, referer: https://domain.tld/doku.php
172.19.0.10 - - [06/Apr/2020:02:59:13 +0000] "GET /lib/tpl/bootstrap3/iconify.php?prefix=mdi&icons=magnify,wrench,account,toolbox,file-document-outline,palette,home-account,share-variant,twitter,linkedin,facebook,pinterest,telegram,whatsapp,yammer,reddit,view-list,pencil,calendar,chevron-up,folder-open,folder,chevron-down HTTP/1.1" 500 -
```

**Comment by giterlizzi** [comment]
Hi,
seems a known Bitnami Docker problem (bitnami/bitnami-docker-dokuwiki#37).

I have pushed a workaround for testing in a separate branch.

To install the patch:
1. Open Administration --> Extension Manager --> Manual Install
2. Install From URL: https://github.com/giterlizzi/dokuwiki-template-bootstrap3/archive/hotfix/bitnami-doku-inc.zip
3. Install

Thanks!

**Comment by PixiBixi** [comment]
Thank you very much, i do have my icons now!

Thanks for your wonderful work over the years o/

**Comment by giterlizzi** [comment]
Thanks ;)

Now I apply this patch in master branch and in my DokuWiki plugins (Bootstrap Wrapper, Icons, etc.).

Joseph!
