### ISSUE TITLE
On Chrome: Section Edit now jumping around since update

### ISSUE THREAD

**Issue by lizat** [giterlizzi/dokuwiki-template-bootstrap3#464]
### Description

Since I updated On Chrome only (OK on FF) The section edit buttons jump around and cannot always be selected - sometimes if I scroll a little the jumping stops.

### Steps to reproduce

Just try to edit a block

### Versions

* [Bootstrap3 Template]: 2020-04-04
* [DokuWiki]; Greebo
* [Plugins]: too many to list, but none added since updated BS3
* [PHP]: 7.3.16
* [Browser] Chrome & Firefox

### Screenshots or Logs

https://www.loom.com/share/2b782d7ae72145648f5cccd4f403c4b7

### Sample page or snippet

[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by kaapyth0n** [comment]
Same for me, you can try in Chrome and Safari
http://gidrologo.ru/wiki/dokuwiki_test
login: test
pass: test

**Comment by giterlizzi** [comment]
@lizat @kaapyth0n 

Thanks for your detailed descriptions and DW access.
I have pushed a fix in master branch for this "bizarre" bug.

Please reinstall the template again!

Joseph!

**Comment by lizat** [comment]
Hi Joseph,

Thank you for your rapid response! And thank you for such a fabulous template, I love it

Liz
