### ISSUE TITLE
html markup issues

### ISSUE THREAD

**Issue by sioc-de-narf** [giterlizzi/dokuwiki-template-bootstrap3#465]
hello,
google is saying there is code error in the page of my wiki. 
Which means some robots have issues with the code, like Google losing Search's rich results for those page.
That happened after I updated your plugin.

Could you look at https://validator.w3.org/nu/?doc=https%3A%2F%2Ftousrolistes.fr%2Fwiki%2Fdoku.php for the errors ?

Thanks

**Comment by giterlizzi** [comment]
Fixed "itemref/itemprop" issue in master branch.

Please reinstall the template again.

Joseph
