### ISSUE TITLE
section-editing mouse flickering, when trying to click on "Bearbeiten/edit"

### ISSUE THREAD

**Issue by virk** [giterlizzi/dokuwiki-template-bootstrap3#467]
**REMARK:** I JUST REINSTALLED THE TEMPLATE AND EVERYTHING IS FINE AGAIN; PROBABLY THE MISTAKE WAS ON MY SIDE. REGARDS virk :-)

### Description

I recently updated bootstrap3 to version of 04.04.2020.
Now mouse cursor is flickering when I try to make use of section editing; the content below the "bearbeiten/edit"-field seems to be moved "one line" upwards.
### Steps to reproduce

1. Create a page with

==== 07.04.2020 ====
  * Test

==== 07.04.2020 ====
  * Test

==== 07.04.2020 ====
  * Test

==== 07.04.2020 ====
  * Test

...
...

2. Have dokuwiki configured that section-editing is working (I currently do not remember, whether this is a core function or done somehow by a plugin)

3. Go to page you created in 1. and try to edit a section. Here then the content below moves one line upwards and you get difficulties in hitting the "bearbeiten" or "edit"-button.
### Versions

* [Bootstrap3 Template] current
* [DokuWiki] current
* [Plugins] a lot
* [PHP] 5.6.30 and 7.3.11 on another computer
* [Browser] Safari, Firefox, Chrome

In the attached photo it can be seen, what happened: I clicked on the "Bearbeiten"-button. The content below and with this checkbox moved upwards, but the mouse-cursor remained at its former position, roughly top-left of box with "07.04.2020".

This happened similarily on three different browsers.

![bootstrap](https://user-images.githubusercontent.com/451702/78687515-895abd00-78f4-11ea-8eb5-65c4e9a173de.png)

**Comment by giterlizzi** [comment]
Hi @virk thanks for reporting this issue.

The issue was solved with an hotfix to master branch (see #464).

Please reinstall the template again.

At your disposal,
Joseph

**Comment by virk** [comment]
So I did. Thank you for your fast response. Works fine now as I already updated my initial post.
