### ISSUE TITLE
No TOC in navbar

### ISSUE THREAD

**Issue by Ohkami** [giterlizzi/dokuwiki-template-bootstrap3#469]
### Description

when TOC in setting "_tpl»bootstrap3»tocLayout"_ put on _"layout"_, there is no TOC in navbar.

### Steps to reproduce

Bug is here in a new, fresh install (dokuwiki stick)

### Versions

* [Bootstrap3 Template] 2020-04-04
* [DokuWiki]  2018-04-22 "Greebo" / doskuwikistick
* [Plugins] : none
* [Browser] : all

![TOC problem](https://user-images.githubusercontent.com/55941477/78913985-1daa5880-7a8a-11ea-9595-4daff6df6bbe.png)

Thanks for your great template.

**Comment by giterlizzi** [comment]
Hi, i have pushed in master branch an hotfix can solve this issue.

Please reinstall the template again from Extension Manager.

Thanks!
Joseph.
