### ISSUE TITLE
After upgrading to v2020-04-04.The menu in the upper right corner does not display submenu issues.

### ISSUE THREAD

**Issue by ccinoo** [giterlizzi/dokuwiki-template-bootstrap3#470]
### Description

After upgrading to v2020-04-04.The menu in the upper right corner does not display submenu issues.

### Steps to reproduce

Move the mouse to the menu in the upper right corner, the submenu will not be displayed automatically.

### Versions

* [Bootstrap3 Template]
Template v2020-04-04 (hotfix/20200407)
* [DokuWiki]
Release 2018-04-22 "Greebo"
* [Plugins]
CKEditor editor CSS tool
History Cleanup
* [PHP]
PHP7.1
* [Browser]
Chrome 80.0.3987.149
### Screenshots or Logs

![image](https://user-images.githubusercontent.com/30647119/78970465-f3b16e80-7b3b-11ea-86e7-a215c5c642a7.png)

**Comment by borrrsch** [comment]
I also have that issue. Browser dev panel:
Error: Bootstrap's JavaScript requires jQuery bootstrap.min.js:6:37
    <anonymous> https://zyfra.site/lib/tpl/bootstrap3/assets/bootstrap/js/bootstrap.min.js:6

**Comment by giterlizzi** [comment]
Hi,
Please verify if you see errors in JS console and purge the DokuWiki JS Cache via ``http://<domain>/lib/exe/js.php?purge=true`` URL and clear the Browser cache.

Joseph

**Comment by ccinoo** [comment]
> I also have that issue. Browser dev panel:
> Error: Bootstrap's JavaScript requires jQuery bootstrap.min.js:6:37
> https://name/lib/tpl/bootstrap3/assets/bootstrap/js/bootstrap.min.js:6

What I see in the console is the following error:

`Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6
bootstrap3-typeahead.min.js:1 Uncaught TypeError: Cannot read property 'fn' of undefined
    at bootstrap3-typeahead.min.js:1
    at bootstrap3-typeahead.min.js:1
    at bootstrap3-typeahead.min.js:1
(anonymous) @ bootstrap3-typeahead.min.js:1
(anonymous) @ bootstrap3-typeahead.min.js:1
(anonymous) @ bootstrap3-typeahead.min.js:1
fa.js:38 Uncaught ReferenceError: DOKU_TPL is not defined
    at fa.js:38
    at fa.js:177
(anonymous) @ fa.js:38
(anonymous) @ fa.js:177
script-cmpr.js:1 Uncaught ReferenceError: DOKU_BASE is not defined
    at script-cmpr.js:1
    at script-cmpr.js:1
(anonymous) @ script-cmpr.js:1
(anonymous) @ script-cmpr.js:1
jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:20 JQMIGRATE: Migrate is installed, version 3.0.0
jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2 Uncaught TypeError: jQuery(...).typeahead is not a function
    at HTMLDocument.<anonymous> (js.php?t=bootstrap3&tseed=156c5021c6ca21a0b57f5d1f500c0430:1)
    at j (jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2)
    at k (jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2)
(anonymous) @ js.php?t=bootstrap3&tseed=156c5021c6ca21a0b57f5d1f500c0430:1
j @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
k @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
start:1 Error while trying to use the following icon from the Manifest: https://www.wiki.com/wiki/_media/wiki/dokuwiki.svg (Download error or resource isn't a valid image)
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

**Comment by ccinoo** [comment]
> Hi,
> Please verify if you see errors in JS console and purge the DokuWiki JS Cache via `http://<domain>/lib/exe/js.php?purge=true` URL and clear the Browser cache.
> 
> Joseph

Thanks for the reply, I have tried to clear the browser cache and the problem is not resolved.
The error message I saw is from the screenshot below.

![image](https://user-images.githubusercontent.com/30647119/78992382-b1088a00-7b6d-11ea-9e9c-f888da68485c.png)

**Comment by phy25** [comment]
Have you done http://<domain>/lib/exe/js.php?purge=true ? There is also a server cache. Alternatively you can go to your DokuWiki configuration and save without any changes.

**Comment by ccinoo** [comment]
> Have you done http:///lib/exe/js.php?purge=true ? There is also a server cache. Alternatively you can go to your DokuWiki configuration and save without any changes.

Thank you for your reply. I followed the steps below and the problem was not resolved.
1. Execute http: ///lib/exe/js.php? Purge = true
2. Chrome browser clears the cache

**Comment by phy25** [comment]
Could you "go to your DokuWiki configuration and save without any changes" and try again?

**Comment by ccinoo** [comment]
> Could you "go to your DokuWiki configuration and save without any changes" and try again?

Thank you. I followed the steps below and the problem was not resolved.
1. Execute http: ///lib/exe/js.php? Purge = true
2. Chrome browser clears the cache
3. On the wiki configuration page, save without making any changes.


![image](https://user-images.githubusercontent.com/30647119/79033307-c9b18800-7bdf-11ea-8510-68f1b7cea9f0.png)

**Comment by ccinoo** [comment]
I don't know if these html codes are helpful.

![image](https://user-images.githubusercontent.com/30647119/79033381-6e33ca00-7be0-11ea-94bd-4afb10e68d4b.png)

**Comment by giterlizzi** [comment]
You see errors (HTTP 404 or 500) in Network Tab in Developer Console ?

**Comment by ccinoo** [comment]
> You see errors (HTTP 404 or 500) in Network Tab in Developer Console ?

Thank you. Did not see the 200 thought prompt.
![image](https://user-images.githubusercontent.com/30647119/79058967-00060a80-7ca7-11ea-9171-08ff034453e4.png)

**Comment by Ryonez** [comment]
How are you guys running that url? All it does is open that page as text.

**Comment by Ryonez** [comment]
In any case I just installed this on a fresh installation, and updated another and both have this issue.

**Comment by ccinoo** [comment]
> 无论如何，我只是将其安装在全新安装上，然后更新了另一个安装，并且两者都存在此问题。

Before the problem was resolved, I temporarily replaced it with another template.

**Comment by Ryonez** [comment]
Gave that a go, reverted to the default template, then came back, no joy.

**Comment by giterlizzi** [comment]
@ccinoo @Ryonez in develop branch i have a new dispatcher for CSS asset and have removed some legacy code for JS asset (now use the default DokuWiki ``js.php`` dispatcher) can solve this issue.

Joseph

**Comment by Ryonez** [comment]
@giterlizzi 
That breaks the site:
![image](https://user-images.githubusercontent.com/16157130/82132657-26830c80-9836-11ea-97b2-278770d52ac8.png)

And those urls don't "run". As I said above, all it does is display text.

**Comment by giterlizzi** [comment]
@Ryonez Apache error_log ?

**Comment by Ryonez** [comment]
![image](https://user-images.githubusercontent.com/16157130/82145019-ec4c5600-989b-11ea-83f2-58f7e7eedb72.png)

Found out I can use the last good commit here until this is fixed: https://github.com/giterlizzi/dokuwiki-template-bootstrap3/archive/v2019-05-22.zip

**Comment by giterlizzi** [comment]
Seems a non standard DokuWiki installation.

Where is the ``DOKU_INC`` directory path?

**Comment by Ryonez** [comment]
It's a docker container maintained by linuxserver.iso [here](https://hub.docker.com/r/linuxserver/dokuwiki/). The dockerfile git can be found [here](https://github.com/linuxserver/docker-dokuwiki).

App directory structure can be found [here](https://github.com/linuxserver/docker-dokuwiki/blob/master/root/etc/cont-init.d/50-config).

**Comment by giterlizzi** [comment]
Thanks! Added LinuxServer.io Docker image support.

Please re-install the develop version.

**Comment by Ryonez** [comment]
That seems to have done it, thank you!
