### ISSUE TITLE
Revert the using of the whole screen width 

### ISSUE THREAD

**Issue by CBDFactum-com** [giterlizzi/dokuwiki-template-bootstrap3#472]
### Description

What do I have to set that in the current version 2020-04-04 not the whole screen width is used. This doesn't look nice and is really tiresome on high resolution as the eye has always to move from left to right.

### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

* [Bootstrap3 Template] 2020-04-04
* [DokuWiki]
* [Plugins]
* [PHP]
* [Browser]

### Screenshots or Logs

[Paste your logs or attach the screenshot]

### Sample page or snippet

[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by jomority** [comment]
You have to set `tpl»bootstrap3»fluidContainer` to `false`.

**Comment by CBDFactum-com** [comment]
Where do I have to set it? Sorry, I don't understand what you mean.

**Comment by jomority** [comment]
Go to your settings page (e.g. [[https://yourwiki.example.com/doku.php?do=admin&page=config]]), search for `fluidContainer`, uncheck the checkbox and save.

**Comment by CBDFactum-com** [comment]
Thank you very much, it's fixed.
