### ISSUE TITLE
Conflict with Snippets plugin - Snippets not displaying as expected

### ISSUE THREAD

**Issue by lizat** [giterlizzi/dokuwiki-template-bootstrap3#473]
### Description

I use the Snippets plugin: https://www.dokuwiki.org/plugin:snippets

Instead of the pop-up as described in the documentation I got this: https://www.screencast.com/t/qzQgGpzJ. So, no icons,( mauve background is from the template styles), no notes on the right, no icons or checkboxes. And, if I click the item it is a regular link to the page which is then displayed in the pop-up.

I reported to the Snippets author and on investigation he says it is a conflict 

> Yes, it is bootstrap3.  ... I do get the underlined links and the generally corrupted left-hand panel of the pop-up.  You'll have to take this up with bootstrap3.    He does some non-standard things that sometimes interfere with plugins.

### Steps to reproduce

1.  Install Snippets plugin
2.  Create a couple of pages for testing purposes
3.  Create a page with the list of snippets as a unordered list
4. Edit any test page and click the snippets icon, check the pop-up. 

**Expected behavior:** [What you expected to happen]

The popup should look like this:
https://www.screencast.com/t/EMpDCJ23Y

**Actual behavior:** [What actually happened]
see above

### Versions
Latest of all: 
* [Bootstrap3 Template] latest
* [DokuWiki ]latest
* [Plugins] latest
* [PHP] 7.3
* [Browser] Chrome & Firefox latest

**Comment by giterlizzi** [comment]
Hi, in develop branch i have committed new functionalities (new CSS/JS dispatcher) can solve this issue.

**Comment by lizat** [comment]
Guiseppe,

Any update on progress?
Does your last comment mean I could apply an update? I don't know how if so... can you explain thx

liz
