### ISSUE TITLE
content appears twice

### ISSUE THREAD

**Issue by jamesLZW** [giterlizzi/dokuwiki-template-bootstrap3#474]
why same content will appear twice?when i use dokuwiki theme, it is back to normal.
![image](https://user-images.githubusercontent.com/20952015/80215057-6a875500-866e-11ea-8e6d-d9da4882cd1b.png)

**Comment by giterlizzi** [comment]
This Wiki is online ? What is the version of Bootstrap template ?

Thanks,
Joseph
