### ISSUE TITLE
dokuwiki hook page for footer not working

### ISSUE THREAD

**Issue by darren-henderson** [giterlizzi/dokuwiki-template-bootstrap3#476]
As the title indicates....
 
This is with the 2020-04-04 release.

The dokuwiki hook page for :footer isn't working. It does seem to be noticed as a horizontal line  does appear if you have such a  page but the page source is missing the content of the file. Adding a 
$TEMPLATE->includePage('footer') near 

            // Footer DokuWiki page
            require_once('tpl/footer.php');

in lib/tpl/bootstrap3/main.php will cause the file contents to appear but it's not clear to me that that is the "fix" 

The other hooks that I've tried (including topheader and pagefooter) work as expected.

**Comment by giterlizzi** [comment]
Hi,
thanks for reporting this issue. Now the footer is visible without set ``showWikiInfo`` option.

Please reinstall the template again in Extension Manager.

Joseph
