### ISSUE TITLE
disable "jump to top"

### ISSUE THREAD

**Issue by firechhe** [giterlizzi/dokuwiki-template-bootstrap3#477]
Hello,

I want to disable the "jump to top" (dokuwiki_top" function. My problem is that this button expands the template and I have not enough space on mobile devices.

Is there a possibility to disable this button?

![01](https://user-images.githubusercontent.com/43295016/81102922-9927ea00-8f10-11ea-852d-5af97994f149.jpg)

**Comment by phy25** [comment]
As an alternative, you could hide them with CSS in `conf/userstyle.css` (https://www.dokuwiki.org/devel:css#user_styles):

```css
.back-to-top{display: none;}
```

**Comment by firechhe** [comment]
Hi,
I have created a userstyle.css in the conf folder (there was no userstyle.css, so I created one). The only content of this userstyle.css is

`.back-to-top{display: none;}`

But the "jump to top" is still displayed.

**Comment by giterlizzi** [comment]
I suggest to use ``visibility:hidden`` because the button is displayed on page scroll by adding ``display:inline`` CSS rule.

**Comment by firechhe** [comment]
I used now:

`.back-to-top{display: none !important;}`

and this works for me.
