### ISSUE TITLE
Hook pages on root namespace page, not just children

### ISSUE THREAD

**Issue by takuy** [giterlizzi/dokuwiki-template-bootstrap3#478]
### Description

I'm not sure if this is moreso a bug or feature requet, or if it's the template or core DokuWiki, but figured I would post this here for initial evaluation and see if this can be fixed on the Template side. 

It looks like the behavior is ultimately decided by https://xref.dokuwiki.org/reference/dokuwiki/nav.html?inc/template.php.source.html#l1558
and
https://xref.dokuwiki.org/reference/dokuwiki/nav.html?inc/pageutils.php.source.html#l751

### Steps to reproduce

1. Have a namespace and page named: rsonly
2. Create rightsidebar page for said namespace: rsonly:rightsidebar
3. create page under namespace: rsonly/page1

**Expected behavior:** [What you expected to happen]

Sidebar appears on the page named "rsonly" and pages under the namespace rsonly (ie rsonly/page1)

**Actual behavior:** [What actually happened]
rightsidebar appears only appears on pages under the namespace, not the root page ("rsonly")

### Versions

* Bootstrap3 Template: 2020-04-04
* DokuWiki: 2018-04-22b "Greebo"
* PHP 7.3
* Chrome 81

**Comment by phy25** [comment]
I believe this is intended, please read https://www.dokuwiki.org/config:sidebar and https://www.dokuwiki.org/faq:sidebar

**Comment by takuy** [comment]
Yes, seems like it's the current behavior due to Dokuwiki's use of "nearest page" but I would really like having a sidebar on the namespaces root page. I'm not sure if it would make more sense to add as a config option in Dokuwiki itself or have it as a feature in this template. What do you think?

**Comment by giterlizzi** [comment]
You can create a sidebar in root namespace (``:rightsidebar``) or move/rename your ``rsonly`` page in ``rsonly:start`` for use ``rsonly:rightsidebar`` sidebar.

**Comment by takuy** [comment]
Moving the root page to a :start page complicates the URL and navigation
more though. Kind of an extraneous solution. I'll see if I can submit a PR
to Dokuwiki's core to solve this scenario.
