### ISSUE TITLE
Google Search Errors: BreadcrumbList + ListItem

### ISSUE THREAD

**Issue by willmcknight** [giterlizzi/dokuwiki-template-bootstrap3#480]
### Description

Google search console throws two errors with May 2020 code.  _**P.S.  Thanks on the template, it's great!!!**_

### Steps to reproduce

1. Installed newest template
2. Wiki Config Setting:
___ Display: Breadcrumbs = 7
___ Display: YouAreHere = Checked
3. Google Search Console https://search.google.com
4. Submitted XML sitemap to Google
5. Get email from Google showing errors, missing items for both BreadcrumbLIst and ListItem

NOTE --> If Wiki config is set as below, then NO error:
___ Display: Breadcrumbs = 0 (disabled)
___ Display: YouAreHere = UNChecked

### Versions

- [Bootstrap3 Template] latest
- [DokuWiki] latest

### Screenshots or Logs

![image](https://user-images.githubusercontent.com/22354931/82731006-c0c0d580-9cb8-11ea-865c-d749fc62c636.png)

![image](https://user-images.githubusercontent.com/22354931/82731020-d930f000-9cb8-11ea-99f7-5e94f1b6b1a7.png)

### Sample page or snippet

**BreadcrumbList**
` <div class="dw__youarehere">
        <ol class="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList"><li>You are here</li><li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a href="/start"   itemprop="item" title="start"><span itemprop="name"><i class="mdi mdi-home"></i></span></a></li></ol>    </div>`

**ListItem**
`<div class="dw__youarehere">
        <ol class="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList"><li>You are here</li><li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a href="/start"   itemprop="item" title="start"><span itemprop="name"><i class="mdi mdi-home"></i></span></a></li></ol>    </div>`

**Comment by giterlizzi** [comment]
Fixed in development branch.
