### ISSUE TITLE
Navbar Items Improperly Formatted

### ISSUE THREAD

**Issue by TheZachh** [giterlizzi/dokuwiki-template-bootstrap3#481]
### Description
As of the latest version of this template, when I install bootstrap3 into a freshly installed copy of Dokuwiki, I've noticed the navbar items have a weird :active state. I've tried to correct this but can't find where this is defined in the theme. 

This happens in all themes, regular, default, bootswatch, etc. The navbar items elevate when in an active state. I've tried to use CSS to correct it but it doesn't seem to take. Why is this happening? 

![Screenshot 2020-05-28 13 22 12](https://user-images.githubusercontent.com/19249281/83178668-7be8d480-a0e6-11ea-86c8-fe4ca138592c.png)

Navbar code: 
![Screenshot 2020-05-28 13 29 42](https://user-images.githubusercontent.com/19249281/83178881-ce29f580-a0e6-11ea-8fea-75b67513b037.png)

PS. Bootstrap 3.3.7-3.4.1 are ancient. Will we ever be getting a bootstrap4 template or do I need to try and hack this one to pieces to upgrade it? :P 

Thanks for your help.

**Comment by jiyuxiongdi** [comment]
Try wrapping the title like this:
`[[:ahs:index | {{AHS}} ]]`

**Comment by giterlizzi** [comment]
@TheZachh Do you have installed other plugins ?

**Comment by lukas2511** [comment]
It seems that dokuwiki is now handling the curid marking using javascript ("currentIDHighlitghting" in lib/scripts/page.js), and this probably breaks the replacement rules inside this template.

**Comment by giterlizzi** [comment]
@TheZachh Added support for Hogfather in last commit in develop branch

**Comment by giterlizzi** [comment]
Today is Hogfather and Bootstrap Template release day!
