### ISSUE TITLE
on upgrade, upper right doku menus do not work

### ISSUE THREAD

**Issue by waxweb** [giterlizzi/dokuwiki-template-bootstrap3#485]
hi, I'm just a simple enduser :) 
I have the most recent version of your excellent theme, thank you for your work!
When I update to the latest version of dokuwiki,
the upper right administation menus cannot be opened...
trying to use them leads to a page reload.
Thus I can't administer, logout, etc.

I have cleaned all caches, and also done the purge css etc commands you list in one of the bugs below. Perhaps I've not done well? 

is there a simple reason for this? It works well in the older greebo.b version, 
but I"m also having troubles upgrading to .c
and of course to the current 'hogfather'
thanks for any simple advice!

David Blair

**Comment by giterlizzi** [comment]
Follow this issue #483
