### ISSUE TITLE
Navigation and Admin section not accessible/working on Tablet/Mobile Version

### ISSUE THREAD

**Issue by raspifriend** [giterlizzi/dokuwiki-template-bootstrap3#486]
Installed the development version of the template. On my desktop computer the header to get to the settings and admin section are working fine. Also the navigation.
When using my tablet I can click on the icon for the settings or the navigation, but nothing happens. The Icon gets gray but no page is loaded. Same behavior in Firefox and Chrome.

I would like the give some more information - due to that I'm completely new to this, I don't know where to find the error log files. Sorry.
![Screenshot_20200604_135623_org mozilla firefox](https://user-images.githubusercontent.com/4411054/83754338-1d829f80-a66c-11ea-96e6-642b54b49b7d.jpg)

**Comment by phy25** [comment]
Duplicate with #483.
