### ISSUE TITLE
How to get rid of section link icon?

### ISSUE THREAD

**Issue by jiyuxiongdi** [giterlizzi/dokuwiki-template-bootstrap3#488]
I cannot figure out how to disable the section link icon. Anyone can help? Thanks!
![Screenshot (182)_LI](https://user-images.githubusercontent.com/53189752/84227519-392bf100-ab17-11ea-85f7-cbd2c957ad46.jpg)

**Comment by giterlizzi** [comment]
This is AncorJS component. Disable ``useAnchorJS`` option.
