### ISSUE TITLE
Headlines with 4 "=" symbols do not appear in ToC

### ISSUE THREAD

**Issue by Regensburga** [giterlizzi/dokuwiki-template-bootstrap3#491]
### Description

The table of content only shows headlines with 6 or 5 "=" symbols but not with 4 "="

Example:
====== Test ====== ⇒ Appears in ToC
===== Test ===== ⇒ Appears in ToC
==== Test ==== ⇒ Does not appear in ToC

### Versions

* Bootstrap3 Template v2020-04-04 (hotfix/20200505)
* DokuWiki 2018-04-22b "Greebo"

**Comment by giterlizzi** [comment]
This is a behavior of template if ``tocCollapseSubSections`` option are ``on`` (Collapse all sub-sections in TOC to save space).
The hidden sub-sections are displayed automatically when the user scroll the page.
