### ISSUE TITLE
Problem with PHP safe mode: ON

### ISSUE THREAD

**Issue by DrakMrak** [giterlizzi/dokuwiki-template-bootstrap3#492]
I see one more problem... (**PHP 7.3 / safe mode: ON / Last version Dokuwiki: Release rc-2020-06-09 "Hogfather" RC3 / Template: Template v2020-04-04 (develop/20200611)**)
in file: **simple_html_dom.php**

I must comment this
24: //set_time_limit(0);
25: //ini_set('max_execution_time', 0); - not set to zero!! (5-300)

**My provider** does not allow set set_time_limit(X) - and dokuwiki appear warning message when trying to change it!
"Warning: set_time_limit() has been disabled for security reasons in /data/web/virtuals/52324/virtual/www/lib/tpl/bootstrap3/inc/simple_html_dom.php on line 24"

**I can set max_execution_time from 5 to 300, and I have set 300 - but it is not always enough!**
I can not set set_time_limit(0) - among other things, this is not recommended for **security reasons** !!

"Warning - This function has no effect when PHP is running in safe mode. There is no workaround other than turning off safe mode or changing the time limit in the php.ini."

**Comment by giterlizzi** [comment]
Fixed in develop branch!
