### ISSUE TITLE
Show custom links in the page footer

### ISSUE THREAD

**Issue by ilu33** [giterlizzi/dokuwiki-template-bootstrap3#496]
showBadges showWikiInfo and showLoginOnFooter allow to show DokuWiki info in the page footer. There does not seem to be an option to place custom links to the site imprint or privacy statement or other necessary legal stuff in the footer. Having those mandatory links in page footer instead of menu is almost standard nowadays.

**Comment by ilu33** [comment]
Never mind, I figured it out: You need to put a file named footer.html in the directory /conf/tpl/bootstrap3.
Content example: 
`{{fa>info?fw}} [[:<namespace>:imprint|Imprint]] {{fa>info?fw}} [[:<namespace>:privacy|Privacy]] {{fa>sign-in?fw}} [[:start?do=login&sectok=|Login]]`

Keep up the good work!

**Comment by giterlizzi** [comment]
Instead of ``footer.html`` you can create ``:footer`` page from DokuWiki editor.

For more informations see the DokuWiki hooks in https://www.dokuwiki.org/template:bootstrap3:hooks

**Comment by ilu33** [comment]
There was a file footer.txt under /data/pages with the same content when I "inherited" that wiki and I remember that it worked 2 years ago but not anymore.
