### ISSUE TITLE
Can't install using Extension Manager on a fresh dokuwiki 

### ISSUE THREAD

**Issue by Eyji** [giterlizzi/dokuwiki-template-bootstrap3#505]
Hey,

I've just installed my dokuwiki on a stick. 
I tried installing your template but the installation process never finishes. 
Then whenever I get to the "installed templtes" tab, an "Update" button appears and gives me this error code : 
`Fatal error: Maximum execution time of 120 seconds exceeded in E:\dokuwiki\vendor\splitbrain\php-archive\src\Zip.php on line 211`

EDIT : successfully installed by extracting the folder in lib/tpl

**Comment by giterlizzi** [comment]
Seems a particular problem with php-archive because i tried to replicate this issue in my lab without success. Sorry!
