### ISSUE TITLE
JS Anchor Links missing after 28.08.20 update

### ISSUE THREAD

**Issue by senorandy** [giterlizzi/dokuwiki-template-bootstrap3#509]
It looks like the Javascript improvements in the 28.08.20 version may have killed the JS anchor links next to the headings.

Dokuwiki Version: Hogfather    Bootstrap 3 Version: 28.08.2020

The option UseanchorJS is activated in the template configuration.

They were working with Hogfather and the 29.07.2020 template version. Thanks.

**Comment by londoss** [comment]
I supports this

Release 2018-04-22c "Greebo".

**Comment by alexandertse** [comment]
I support this too. I use it for internal linking.

**Comment by nurzu** [comment]
i'm facing the same issue

**Comment by giterlizzi** [comment]
Fixed in develop release

**Comment by londoss** [comment]
> Fixed in develop release

Thank you for information. Any idea of release date in new version?

**Comment by giterlizzi** [comment]
Hi, today i have released a stable release of template. Now you can update the template using Extension Manager.
