### ISSUE TITLE
Unable to rename using the Move Plugin, issue with the class.

### ISSUE THREAD

**Issue by Dpons039** [giterlizzi/dokuwiki-template-bootstrap3#512]
### Description

Unable to rename using the Move Plugin, issue with the class.

### Steps to reproduce

1. Install Plugin Move plugin
2. Go to a Page and click the rename icon

**Expected behavior:** [What you expected to happen]
Prompt to rename the page.

**Actual behavior:** [What actually happened]
Error message:
Action unknown: menuitem

### Versions

* [Bootstrap3 Template] 2020-08-28
* [DokuWiki] Release 2020-07-29 "Hogfather"
* [Plugins] 2018-04-30
* [PHP] 7.3
* [Browser] Any

### Screenshots or Logs
![image](https://user-images.githubusercontent.com/3227283/95011765-58eda480-0633-11eb-950b-c38de13438d4.png)

There are some posts about this, but I'm not sure how to make it work on this template.
https://github.com/michitux/dokuwiki-plugin-move/issues/150
It seems can be fixed on the theme:
https://github.com/LeonStaufer/material-dokuwiki/issues/33

### Sample page or snippet

```
<a href="/home?do=menuitem" title="Rename Page" rel="nofollow" class="menuitem menuitem plugin_move_page "><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M18,4V3A1,1 0 0,0 17,2H5A1,1 0 0,0 4,3V7A1,1 0 0,0 5,8H17A1,1 0 0,0 18,7V6H19V10H9V21A1,1 0 0,0 10,22H12A1,1 0 0,0 13,21V12H21V4H18Z"></path></svg><span>Rename Page</span></a>
```

**Comment by giterlizzi** [comment]
Problem caused by JS error. Please check your JS console.

**Comment by sokolgeo** [comment]
> Problem caused by JS error. Please check your JS console.

How is this a solution? For me the problem only appears in mobile view.

How about applying the approach from https://github.com/michitux/dokuwiki-plugin-move/issues/150#issuecomment-611191840  ?

**Comment by giterlizzi** [comment]
Move plugin use a JS event for display a modal for rename the current page, if the browser encounters a JS error, execution of all scripts on the page is compromised. The move plugin uses an unknown "action" for DokuWiki, so I don't execute the JS event, the browser follows the link with the unknown action `?do=menuitem`.

In your JS console, is there any information about the error? (plugin or template)

Hogfather introduces the `defer` JS attribute for speedup the page loading, but some plugins not work properly with this option. Can you try disabling the `defer_js` option in Configuration Manager?

Joseph

**Comment by sokolgeo** [comment]
Here are two items I receive in Firefox JS console when trying to rename the item in mobile view:

> LoginRecipes: getRecipes: falling back to a synchronous message for: http://127.0.0.1 LoginRecipes.jsm:266:9
> 
> TypeError: gRecipeManager is null LoginManagerParent.jsm:119:3
>     <anonymous> resource://gre/modules/LoginManagerParent.jsm:119

when I disable 'defer_js' in Dokuwiki settings and try renaming the page again, I still get the 'Action unknown: menuitem' error message, without any items appearing in JS console.

Does the above help?

**Comment by phy25** [comment]
What browsers have you tried? What other plugins do you have?

**Comment by Dpons039** [comment]
I'm still experiencing the issue, the icon is displayed but upon clicking on it I get the message of the menuitem.
`Action unknown: menuitem`

On the browser Console I get this message:
```
jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2 Uncaught TypeError: e.indexOf is not a function
    at S.fn.init.S.fn.load (jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2)
    at js.php?t=bootstrap3&tseed=050521d02da24435c731b19ea412a1ff:1
```
The mentioned `defer_js` is disabled on the Dokuwiki settings.

**Comment by giterlizzi** [comment]
@Dpons039, The rest of page work correctly (eg. user - page - site tools in header) ?
@sokolgeo, Seems a FF problem. You see the errors with another browser (Chromium, Edge, Opera or another WebKit browser)?

**Comment by Dpons039** [comment]
> @Dpons039, The rest of page work correctly (eg. user - page - site tools in header) ?

Yeah, everything works great. It's only that plugin that is not working since the Hogfather update.

**Comment by sokolgeo** [comment]
> @sokolgeo, Seems a FF problem. You see the errors with another browser (Chromium, Edge, Opera or another WebKit browser)?

@giterlizzi Sorry, I'm running this instance on the PinePhone https://wiki.postmarketos.org/wiki/PINE64_PinePhone_(pine64-pinephone)
Chromium install fails due to flatpak obsolete version, sorry. Firefox is version 78.7.0esr here.
