### ISSUE TITLE
Several js issues after upgrading to Hogfather and latest Bootstrap3

### ISSUE THREAD

**Issue by fibinicci** [giterlizzi/dokuwiki-template-bootstrap3#516]
### Description

Accordion feature does not work if I navigate the dokuwiki as public/anonymous navigation 
Works fine if I am logged in (as admin)

See below screenshot for 3 errors appearing regarding js in the console

### Steps to reproduce

Click on panel title

**Expected behavior:** on click the panel slide up or down

**Actual behavior:** panel always open

### Versions

* [Bootstrap3 Template] latest v2020-08-28
* [DokuWiki] Hogfather
* [Plugins]
* [PHP] 7.3
* [Browser] Chrome

![image](https://user-images.githubusercontent.com/60179195/97743818-87518900-1ae6-11eb-81e0-b3174317025e.png)

**Comment by rgleason** [comment]
See bottom, does any of the 3 things help?
https://github.com/giterlizzi/dokuwiki-template-bootstrap3/issues/490

**Comment by fibinicci** [comment]
it was written in July and I have the latest v2020-08-28 version so I thought these recommendation would not work for me.
And additionnaly I looked at my version and I aleady have the jQuery tv3.5.1.

**Comment by fibinicci** [comment]
I noted today the same problem with tab pane component (also from bootswrapper plugin)
if I navigate the dokuwiki as public/anonymous navigation the page is not displaying as expected, ie the tab pane does not work.
But it works fine if I am logged in (as admin).
The console shows only errors (screenshot above) when not logged in, when logged in there are no errors (only the warnings)
Any idea where this difference comes from?
It seems both related to bootswrapper plugin

**Comment by fibinicci** [comment]
Ok so these issues were not fully related to the upgrades.
One previous issue that I had with buttons (no styling possible) is now solved along with the accordion problem and the tab pane problem.
The **conflict came from the Webcomponents plugin** (from Gerard Nico)
When disabling it, the bootswrapper functions all seem to work fine now whether logged in or as public/anonymous navigation.
