### ISSUE TITLE
Languages don't apply as intended

### ISSUE THREAD

**Issue by nkreer** [giterlizzi/dokuwiki-template-bootstrap3#519]
### Description

While filing #518, I came across the issue that template language labels do not seem to apply properly when a special version of a given language is installed. E.g., for German, there are "de-informal" and "de" language packs available for Dokuwiki. The bootstrap3 template however only applies to "de" and "de-informal" gets to view unlocalized English strings. 

The expected behavior would be that the template ignores what special version of a language is used when there is no direct translation, but already one for the base version of that language. E.g. when I use "de-informal", I should see "de" locales when no "de-informal" locales are available instead of "en" locales.

**Comment by giterlizzi** [comment]
Hi,
actually the template support only ``de`` locale but you can create a PR for create ``de-informal`` language file (see ``lang/<locale>/lang.php``) or join in Transifex teams (#62).

Joseph
