### ISSUE TITLE
Restore wikilink2 to included sidebars

### ISSUE THREAD

**Issue by takuy** [giterlizzi/dokuwiki-template-bootstrap3#520]
**Is your feature request related to a problem? Please describe.**
As described here: https://github.com/giterlizzi/dokuwiki-template-bootstrap3/commit/8241775ae6e96f12c858ba015c3c19b9804b3d40#r42806622

This impacts a local plugin/customization of mine that depended on being able to detect wikilinks that did not link to actual pages (ie had the class wikilink2) - it's a big deviation from the standard DokuWiki functionality as we ll. 

**Describe the solution you'd like**
Perhaps this could be a config option for "don't style links to non-existent pages differently" or a config to define a different class to replace wikilink2.

**Describe alternatives you've considered**
I've commented out the line of code that does this currently. 

**Additional context**

**Comment by giterlizzi** [comment]
Re-added in 4a8e939 in dev branch.
