### ISSUE TITLE
Cannot replace the logo!!

### ISSUE THREAD

**Issue by rainkings** [giterlizzi/dokuwiki-template-bootstrap3#522]
### Description
I want to change the logo of dokuwiki. I replace the picture in lib/tpl/dokuwiki/images/logo.png and lib/tpl/bootstrap3/images/logo.png but it just do not work... I wonder if I do the right thing or just there exists a bug...
Thank u very much if you could help me here.

### Screenshots or Logs

[Paste your logs or attach the screenshot]
![image](https://user-images.githubusercontent.com/39999839/101717504-5e0b1c00-3ada-11eb-9664-4455a0bc16f5.png)

**Comment by phy25** [comment]
Could you try https://www.dokuwiki.org/template:bootstrap3:customizations#change_the_logo_and_favicon?

**Comment by rainkings** [comment]
> Could you try https://www.dokuwiki.org/template:bootstrap3:customizations#change_the_logo_and_favicon?
oh ,Thank you so much!! my bad. Seems I need to redo the replacement....
