### ISSUE TITLE
Bootstrap Settings broken? Unable to click/view.

### ISSUE THREAD

**Issue by Skyridr** [giterlizzi/dokuwiki-template-bootstrap3#525]
When I installed it, I noticed additional bootstrap3 settings. But I'm unable to click/see them:

![image](https://user-images.githubusercontent.com/6794064/102321437-f7747b00-3f7d-11eb-8548-1f6a84a8366e.png)

Debug enabled, with no errors shown. Any reason as to why these show up? Should they be there?

**Comment by giterlizzi** [comment]
Fixed in develop branch

**Comment by sashok2k** [comment]
I have different, but related issue - there is no settings rendered for template under Configuration Manager.
They were there before, but now there is nothing except navigation menu.
![image](https://user-images.githubusercontent.com/20895615/105452308-ae1bf780-5cb0-11eb-93f7-a8b9a3a7f638.png)
Clicking on any of the links do nothing. 
I did attempt to update with version from develop.

**Comment by giterlizzi** [comment]
@sashok2k When you scroll down the page do you see the template section? You have errors in apache error_log or in JS console ?

**Comment by sashok2k** [comment]
@giterlizzi sorry, forgot to inform... this issue was caused by another plugin.. my issue is not relevant
