### ISSUE TITLE
Sidebars - using alternatives & collapsing

### ISSUE THREAD

**Issue by lizat** [giterlizzi/dokuwiki-template-bootstrap3#526]
It would be good to be able use different sidebars (or none) on specific pages - I would like a left sidebar and the standard one works well in almost all circumstances, a few pages need no sidebar and then there is a collection of pages that need a slightly different sidebar. Is this possible?

Is it possible to offer the user the facility to collapse the sidebar?

**Comment by dd1982** [comment]
[Yes - it's possible](https://www.dokuwiki.org/faq:sidebar#sidebar_by_namespace) (and unrelated to the Bootstrap3-template).
