### ISSUE TITLE
Tags extend beyond page limits

### ISSUE THREAD

**Issue by tmo26** [giterlizzi/dokuwiki-template-bootstrap3#529]
### Description

Long list of tags extends beyond page limits

### Steps to reproduce

1. create a long list of tags on a page

**Expected behavior:** Long list of tags stays within page limits

**Actual behavior:** Long list of tags does not stay within page limits (see screenshot below)

### Versions

* [Bootstrap3 Template] Template v2020-08-28 (stable/20200828)
* [DokuWiki] Release 2020-07-29 "Hogfather"
* [Plugins]
```
plugin	a2s
plugin	abbr
plugin	acl
plugin	addnewpage
plugin	authmysql
plugin	authorstats
plugin	authpgsql
plugin	authplain
plugin	batchedit
plugin	bureaucracy
plugin	captcha
plugin	catlist
plugin	cellbg
plugin	cleanup
plugin	clearhistory
plugin	cloud
plugin	color
plugin	columns
plugin	comment
plugin	config
plugin	cookielaw
plugin	csv
plugin	custombuttons
plugin	data
plugin	datatables
plugin	datatemplate
plugin	ditaa
plugin	docnavigation
plugin	enforcesummary
plugin	extension
plugin	feed
plugin	filelist
plugin	folded
plugin	gchart
plugin	gdpr
plugin	gh
plugin	hidden
plugin	hiddenheader
plugin	hidepages
plugin	iframe
plugin	imagemapping
plugin	include
plugin	info
plugin	interwikipaste
plugin	ipban
plugin	loglog
plugin	maintenancemessage
plugin	meta
plugin	move
plugin	multiorphan
plugin	mysql
plugin	nosidebar
plugin	nslist
plugin	nspages
plugin	oauth
plugin	orphanswanted
plugin	outliner
plugin	pagelist
plugin	pagequery
plugin	passpolicy
plugin	popularity
plugin	preregister
plugin	prettytables
plugin	redirect
plugin	revert
plugin	safefnrecode
plugin	searchdefaults
plugin	searchform
plugin	searchindex
plugin	searchstats
plugin	searchtablejs
plugin	semantic
plugin	smtp
plugin	sortablejs
plugin	sqlite
plugin	styling
plugin	tabbox
plugin	tag
plugin	tagalerts
plugin	toolbox
plugin	translation
plugin	unameban
plugin	upgrade
plugin	userhistory
plugin	usermanager
plugin	vshare
plugin	webcode
plugin	wrap
```
* [PHP] 7.0.33-1~dotdeb+8.1
* [Browser] Firefox 84.0.2 shows the described behaviour; Chrome 87.0.4280.88 does not show this behaviour (i.e. Chrome works as expected)

### Screenshots or Logs

![grafik](https://user-images.githubusercontent.com/12309103/103953377-4c04b380-5142-11eb-81a5-600faff3a5a4.png)

### Sample page or snippet

https://openwrt.org/toh/actiontec/actiontec_mi424wr_rev._i#tags

**Comment by giterlizzi** [comment]
Fixed in develop branch

**Comment by tmo26** [comment]
Confirmed, seems to be working now as expected.
