### ISSUE TITLE
Tabbox plugin doesn't work anymore

### ISSUE THREAD

**Issue by tmo26** [giterlizzi/dokuwiki-template-bootstrap3#530]
### Description

Tabbox plugin doesn't work anymore

### Steps to reproduce

1. Create a page with some tabboxes

**Expected behavior:** Tabs are shown

**Actual behavior:** No tabs are shown, but a list of links. Clicking on links shows the content of the tabs.

### Versions

* [Bootstrap3 Template] Template v2020-08-28 (stable/20200828)
* [DokuWiki] Release 2020-07-29 "Hogfather"
* [Plugins]
```
plugin	a2s
plugin	abbr
plugin	acl
plugin	addnewpage
plugin	authmysql
plugin	authorstats
plugin	authpgsql
plugin	authplain
plugin	batchedit
plugin	bureaucracy
plugin	captcha
plugin	catlist
plugin	cellbg
plugin	cleanup
plugin	clearhistory
plugin	cloud
plugin	color
plugin	columns
plugin	comment
plugin	config
plugin	cookielaw
plugin	csv
plugin	custombuttons
plugin	data
plugin	datatables
plugin	datatemplate
plugin	ditaa
plugin	docnavigation
plugin	enforcesummary
plugin	extension
plugin	feed
plugin	filelist
plugin	folded
plugin	gchart
plugin	gdpr
plugin	gh
plugin	hidden
plugin	hiddenheader
plugin	hidepages
plugin	iframe
plugin	imagemapping
plugin	include
plugin	info
plugin	interwikipaste
plugin	ipban
plugin	loglog
plugin	maintenancemessage
plugin	meta
plugin	move
plugin	multiorphan
plugin	mysql
plugin	nosidebar
plugin	nslist
plugin	nspages
plugin	oauth
plugin	orphanswanted
plugin	outliner
plugin	pagelist
plugin	pagequery
plugin	passpolicy
plugin	popularity
plugin	preregister
plugin	prettytables
plugin	redirect
plugin	revert
plugin	safefnrecode
plugin	searchdefaults
plugin	searchform
plugin	searchindex
plugin	searchstats
plugin	searchtablejs
plugin	semantic
plugin	smtp
plugin	sortablejs
plugin	sqlite
plugin	styling
plugin	tabbox
plugin	tag
plugin	tagalerts
plugin	toolbox
plugin	translation
plugin	unameban
plugin	upgrade
plugin	userhistory
plugin	usermanager
plugin	vshare
plugin	webcode
plugin	wrap
```
* [PHP] 7.0.33-1~dotdeb+8.1
* [Browser]
  * Firefox 84.0.2 shows the described behaviour
  * Chrome 87.0.4280.88 shows the described behaviour

### Screenshots or Logs

![grafik](https://user-images.githubusercontent.com/12309103/103955025-b408c900-5145-11eb-9b7b-15119fcfccfd.png)

### Sample page or snippet

https://openwrt.org/toh/netgear/wndr3700

**Comment by Arickx** [comment]
Does [Bootstrap3 Template v2021-03-11](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/releases/tag/v2021-03-11) resolves that [tabbox plugin](https://www.dokuwiki.org/plugin:tabbox) issue?

**Comment by tmo26** [comment]
No, issue persists with Bootstrap3 v2021-03-11.

**Comment by platsch** [comment]
Same problem here.
Not sure if this is actually caused by Bootstrap, or should be taken care of in the plugin itself?

**Comment by platsch** [comment]
@giterlizzi Thx for the quick solution!
