### ISSUE TITLE
Missing section link icon after upgrading to Hogfather

### ISSUE THREAD

**Issue by ehakram** [giterlizzi/dokuwiki-template-bootstrap3#534]
The section link icon is missing. It was present when I was using Greebo. 
I am using the latest available version of all plugins and templates. PHP 7.4. Firefox 86.0
The value of useAnchorJS in /conf/local.php and in /lib/tpl/bootstrap3/conf/default.php are both set to 1

**Comment by giterlizzi** [comment]
Hi, today i have released a stable release of template. Now you can update the template using Extension Manager.

**Comment by ehakram** [comment]
Thank you, will check that soon. Thanks again for your work

**Comment by ehakram** [comment]
Just confirming that it solved it. Thanks
