### ISSUE TITLE
Add support for Google Analytics 4

### ISSUE THREAD

**Issue by rulim34** [giterlizzi/dokuwiki-template-bootstrap3#542]
Google is released [Google Analytics 4 (GA4)](https://developers.google.com/analytics/devguides/collection/ga4) on October 2020, and it should be stable enough for now.

So it would be very nice if we could have an option whether to use Universal Analytics (the old one) or GA4.

**Comment by giterlizzi** [comment]
Added GA 4 support in master branch.
