### ISSUE TITLE
Cannot declare class dokuwiki\Menu\Item\AbstractItem

### ISSUE THREAD

**Issue by himiq** [giterlizzi/dokuwiki-template-bootstrap3#545]
### Description

Cannot declare class dokuwiki\Menu\Item\AbstractItem

### Steps to reproduce

1. Open Edit Page
2. Press icon 'Mediamanager"

### Versions

* Bootstrap3 Template v2021-03-11 (stable/20210311)
* DokuWiki Release 2020-07-29 "Hogfather"
* PHP 7.3.29
* FF 

### Screenshots or Logs

[05-Aug-2021 11:36:43 Europe/Samara] PHP Fatal error:  Cannot declare class dokuwiki\Menu\Item\AbstractItem, because the name is already in use in /usr/local/www/dokuwiki/lib/tpl/bootstrap3/compat/inc/Menu/Item/AbstractItem.php on line 20

**Comment by giterlizzi** [comment]
Hi, please check in doku.php the variable `$updateVersion`.

The compat library are loaded for DokuWiki version older than Grebo.

Joseph

**Comment by himiq** [comment]
$updateVersion = "51.3";

**Comment by Le1b1** [comment]
Same error here, did some manage to fix it?

**Comment by DreamSquareMarkOh** [comment]
In my case, when I installed "Stale plugin", the corresponding error occurred. I solved the problem by deleting it. Use file content search to find php files that use the "AbstractMenu" class and find the cause.

**Comment by Le1b1** [comment]
> I solved the problem by deleting it.

Fixed it for me, too. Thanks!

**Comment by neo7904** [comment]
> > I solved the problem by deleting it.
> 
> Fixed it for me, too. Thanks!

You're welcome. Have a good day!
