### ISSUE TITLE
Navbar unordered list non-functional

### ISSUE THREAD

**Issue by kontu** [giterlizzi/dokuwiki-template-bootstrap3#549]
### Description

:navbar hook does not seem to be properly formatting UL for use

### Steps to reproduce

1- Create :navbar page
2- Create single nested unordered list (example of what I used below)
3- View results

**Expected behavior:**
I expected functionality similar to what is seen here:
![image](https://user-images.githubusercontent.com/5705697/133838557-96a9f7f7-4314-4266-bf11-7adbe3c04932.png)

**Actual behavior:**
Clicking the dropdown doesn't expand or shrink anything, everything is always expanded
![image](https://user-images.githubusercontent.com/5705697/133838370-e4c67ba5-7b30-44f5-97c0-52448d8d86ab.png)

### Versions

* Vanilla Bootstrap3 (and others tested as well)
* Hogfather
* https://pastebin.com/raw/tFSLe8dY
* PHP 7.2.34
* Chrome/Firefox/Edge

### Screenshots or Logs
Included inline above

### Sample page or snippet

Contents of navbar.txt page:
```
*  Community
      * [[:a|Community Rules]]
      * [[:b|Community FAQ]]
  * Space Engineers
      * [[:games:spaceengis:maincluster:sidebar|Draconis Main]]
      * [[:games:spaceengis:dracimp:sidebar|Draconis Impossible]]
  * Minecraft
      * [[:a|Modpack116 ]]
      * [[:d|Vanilla Network]]
~~NOCACHE~~
```

**Comment by giterlizzi** [comment]
@kontu Seems a syntax problem. This snippet work fine:

```
  * Community
    * [[:a|Community Rules]]
    * [[:b|Community FAQ]]
  * Space Engineers
    * [[:games:spaceengis:maincluster:sidebar|Draconis Main]]
    * [[:games:spaceengis:dracimp:sidebar|Draconis Impossible]]
  * Minecraft
    * [[:a|Modpack116 ]]
    * [[:d|Vanilla Network]]
~~NOCACHE~~
```

@virk Thanks for suggestion!
