### ISSUE TITLE
Image resize (include plugin)

### ISSUE THREAD

**Issue by londoss** [giterlizzi/dokuwiki-template-bootstrap3#562]
### Description

When using Include plugin, included page (or section) with image cause to show image in original size without resize to.

### Steps to reproduce

1. Install Include plugin
2. Use to include page or section with image
3. See the image in included page or section to use original size (overflow the page)

**Expected behavior:** Image resize to width of dokuwiki page

**Actual behavior:** Image use size from included page without changing

### Versions

* Release rc2022-06-26 "Igor" RC2
* Template v2021-03-11 (stable/20210311)
* Include
* Chrome latest

### Screenshots or Logs
![page_100](https://user-images.githubusercontent.com/13707503/180779672-cc1aabcc-38ed-4a7c-8b60-24c00722f7cc.png)
![page_25](https://user-images.githubusercontent.com/13707503/180779679-c2b2a6b8-716b-4659-a152-0afdf33329eb.png)

### Sample page or snippet

See https://archi.gov.cz/nap_dokument:architektura_a_sdilene_sluzby_verejne_spravy_cr#pohled_na_identifikaci_a_identifikatory_klientu_vs 

/// code to include section {{section>nap:elektronicka_identifikace_pro_klienty_verejne_spravy#popis_identifikace_klientu_verejne_spravy}}
/// code for image in included section
{{ :nap-dokument:identifikace.png |}}

**Comment by giterlizzi** [comment]
Fixed in master branch.

Please reinstall the template and flush style cache using  `/lib/exe/css.php?purge=true` URL.
