### ISSUE TITLE
Theme switcher does not work until forced reload

### ISSUE THREAD

**Issue by dlehmenk** [giterlizzi/dokuwiki-template-bootstrap3#571]
Hi,

I'm trying out the theme switcher, but have the problem, that the selected theme only loads partially or not at all until I reload with Strg+F5 / disabled Cache. It looks like the css-file isn't even requested by Firefox otherwise, because it is not shown in the network console (not even as cached) on a simple reload, as shown in this image:

![network_log](https://user-images.githubusercontent.com/29567468/192140939-d0cbd438-c776-4cd0-a92d-dc0342116d25.png)

Any idea how to resolve this? Thanks!

**Comment by lukesky333** [comment]
Hi,

I've a similar problem. I see the theme switcher, but nothing is changed. A reload doesn't fix the problem.

I'm using Mozilla Firefox (latest version) with a fully updated DokuWiki installation.

Any idea how to fix that?

**Comment by giterlizzi** [comment]
This issue has been resolved in the latest template release.
