### ISSUE TITLE
Template is disabled, no enable button

### ISSUE THREAD

**Issue by Ppedroo** [giterlizzi/dokuwiki-template-bootstrap3#581]
I can select the template in Configuration Manager, save the changes, but the template always falls back to dokuwiki. In the Extension Manager I can see that the template is disabled and there is no enable button.
Thanks for your help.

**Comment by giterlizzi** [comment]
Hi,
you see errors in JS console or in webserver logs (eg. in Apache access_log) ?

**Comment by Ppedroo** [comment]
Thank you for contacting me. The template now works. It was a few weeks ago
that the enable button was suddenly available after all. Before that I had
adjusted the settings in the Configuration Manager according to my
requirements and then saw that I can now enable the bootstrap3 template. I
haven't figured out what was causing this issue, probably a setting in
Configuration Manager.

Am Do., 2. Feb. 2023 um 23:13 Uhr schrieb Giuseppe Di Terlizzi <
***@***.***>:
