### ISSUE TITLE
Error message after update of the translation plugin

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [giterlizzi/dokuwiki-template-bootstrap3#584]
Hi,
after updating to the current version of the translation plugin, I get the following error message when I open a translated page:
```
2023-02-02 08:16:00
Error: Call to undefined method helper_plugin_translation::getTransItem()
/var/www/html/wiki/lib/tpl/bootstrap3/tpl/translation.php(31)
#0 /var/www/html/wiki/lib/tpl/bootstrap3/tpl/navbar.php(89): include_once()
#1 /var/www/html/wiki/lib/tpl/bootstrap3/main.php(51): require_once('/var/www/html/w...')
#2 /var/www/html/wiki/inc/actions.php(27): include('/var/www/html/w...')
#3 /var/www/html/wiki/doku.php(126): act_dispatch()
#4 {main}
```
I've posted the same issue at the plugin page: [#280](https://github.com/splitbrain/dokuwiki-plugin-translation/issues/280)

Regards
Juergen

**Comment by giterlizzi** [comment]
FIXED in develop branch

**Comment by silke** [comment]
Hi @giterlizzi , thanks for your work on this awesome template! I came across this fixed issue as I ran into the error Juergen reported above. I saw that the last issue in the same milestone v2023-Q1 also seems to be resolved. Are you about to release a new version of the bootstrap template?
Best wishes!

**Comment by LouisOuellet** [comment]
Is there a way within dokuwiki to change the branch for the updates?
