### ISSUE TITLE
SVG logo and favicon

### ISSUE THREAD

**Issue by suedunham** [giterlizzi/dokuwiki-template-bootstrap3#585]
**Is your feature request related to a problem? Please describe.**

I've been trying to change the logo and favicon by using SVG files named `logo.svg` and `favicon.svg`. I've tried placing them in all of the usual locations, but the old images persist. Using `logo.png` and `favicon.ico` works as expected, but I can't get SVGs to work like the other files do.

Is there something I've missed?

**Describe alternatives you've considered**
I've tried putting the SVGs in the following directories.

`[root]`
`/data/media`
`/data/media/wiki`
`/lib/tpl/bootstrap3/images`

I've also tried renaming the default dokuwiki ones to hide them and maybe force the SVG to be used instead. That just seemed to fall back to the ones in `/lib/tpl/bootstrap3/images`. Renaming those removed any logo or favicon from view.

**Additional context**
Adding those SVG files to the `/data/media` directory works as expected in [the ad-hominem template](https://github.com/saschaleib/dokuwiki-template-ad-hominem).

**Comment by giterlizzi** [comment]
Hi, the template use the same DokuWiki (template) configuration for customize the logo and favicon:

https://www.dokuwiki.org/template:bootstrap3:customizations#change_the_logo_and_favicon

Joseph
