### ISSUE TITLE
most Icons in edit-mode are missing

### ISSUE THREAD

**Issue by suther** [giterlizzi/dokuwiki-template-bootstrap3#592]
![image](https://user-images.githubusercontent.com/675096/233100393-7eb5d5b7-ac2a-4b06-9b2b-ead12f4a072b.png)

But if I uncheck this entry, they appear again: 

![image](https://user-images.githubusercontent.com/675096/233100924-73ac1731-a297-4fb7-bbef-10bc3a506693.png)

**Comment by thunderflip** [comment]
I noticed that I have this problem with PHP 8 but no problem with PHP 7.
I don't understand where it could be related with PHP version. I hope this could be a clue to a solution.

**Comment by Er4twXz** [comment]
after editing C:\server\Apache24\htdocs\wiki\lib\tpl\bootstrap3\iconify.php

and inserting at top of the page - after the php declaration

use dokuwiki\Cache\Cache;


and changing 

$cache         = new cache($cache_key, '.js');
to

$cache         = new Cache($cache_key, '.js');

it works - cache is deprecated and replaced by Cache

[iconify.php.txt](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/files/12506292/iconify.php.txt)
