### ISSUE TITLE
Traditional Chinese translation request

### ISSUE THREAD

**Issue by leeyc0** [giterlizzi/dokuwiki-template-bootstrap3#594]
There is no Traditional Chinese translation (zh-tw) available, only (Simplified) Chinese (zh).

I am going to test this template and need Traditional Chinese. I can do the translation, so please add Traditional Chinese in Transifex.

**Comment by giterlizzi** [comment]
I added the language in Transifex. Please log in or PM me your email to add you.

Thanks!

**Comment by leeyc0** [comment]
Sent a join request in Transifex

**Comment by giterlizzi** [comment]
Thanks!
