### ISSUE TITLE
Translation plugin generates error with bootstrap3 

### ISSUE THREAD

**Issue by kavalos2** [giterlizzi/dokuwiki-template-bootstrap3#604]
### Description

After the installation of translation plugin, when the languages were listed in the configuration of the plugin (at the plugin»translation»translations point) the error message appears on the navbar instead of the flags or names of the languages. 

### Steps to reproduce

1. Delete the languages from the configuration, the error message is disappeared
2. Switch of the plugin the error message is disappeared and after switch on again the error message come back
3. Reinstall the plugin the problem is remained
4. Check the plugin on other template. On base  dokuwiki and on 20cones were worked well.

**Expected behavior:** 
The language flags or names should be on the navbar.

**Actual behavior:** [What actually happened]
Error message instead of the language list.

### Versions

* [Bootstrap3 Template] 2022-07-27
* [DokuWiki] Jack Jackrum 
* [Plugins] 2023-12-14
* [PHP]
* [Browser] Mozzila

### Screenshots or Logs

#0 C:\xampp\htdocs\szekeres.com\lib\tpl\bootstrap3\tpl\navbar.php(89): include_once()
#1 C:\xampp\htdocs\szekeres.com\lib\tpl\bootstrap3\main.php(52): require_once('C:\xampp\htdocs...')
#2 C:\xampp\htdocs\szekeres.com\inc\actions.php(27): include('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\szekeres.com\doku.php(126): act_dispatch()
#4 {main}

![image](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/assets/157994148/23cc39ad-dcf3-431a-9016-2b8d38277d08)

**Comment by giterlizzi** [comment]
#584

The fix will be released as soon possible
