### ISSUE TITLE
Heading 1 top margin is reduced after update. How much?

### ISSUE THREAD

**Issue by suedunham** [giterlizzi/dokuwiki-template-bootstrap3#607]
### Description

After installing the 2024-02-06 version, The top margin of the `heading 1` element at the top of a page has been reduced so that it displays higher on the page. This isn't bad per se, but it does muck up some formatting I had up there, and I'd like to know what accounts for the change.

### Steps to reproduce

1. Screencap a page with a `Heading 1` element in a wiki with the previous version of bootstrap3.
2. Update bootstrap3.
3. Compare page with screencap.

**Expected behavior:** I expected no change in the spacing.

**Actual behavior:** The top margin of the `Heading 1` element is reduced.

### Versions

* [Bootstrap3 Template] stable/20240206
* [DokuWiki] 2024-02-06 "Kaos"
* [PHP] 7.4.33
* [Browser] Chrome 121.0.6167.140 (Official Build) (64-bit)

### Screenshots or Logs

These screencaps were made in a customized template with additional `css` formatting. This formatting serves to highlight the effect, so I've gone ahead with it. I have confirmed that an unmodified bootstrap3 template exhibits the same behavior.

**Before**
![bs3_margin_before](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/assets/42522840/f84c90d5-bc2e-4da6-837d-dc1b51e07650)

**After**
![bs3_margin_after](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/assets/42522840/200ad0fe-0be1-4050-91c3-751490626e9d)

### Note

I'm OK with the change, but I'd like to know what the change was. I assume that a bootstrap3 margin class can be added, where need be. What is prompting this is more page content I've placed above the heading that is now too close.

![bs3_margin_icons](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/assets/42522840/8c85c370-a85b-47c7-9c9b-97167b33dd3c)

**Comment by giterlizzi** [comment]
FIXED in master.

Thanks!
