### ISSUE TITLE
Edit mode when not logged in, shows textarea field with source text "as button" (includes fix)

### ISSUE THREAD

**Issue by johngnl** [giterlizzi/dokuwiki-template-bootstrap3#611]
### Description

Edit mode when not logged in, shows textarea field with source text "as button"

### Steps to reproduce

1. This happens on a DokuWiki page that a user can read but _cannot_ edit
2. Click on 'Edit' button (or add ?do=edit to the url) to view the source text.
3. The source text will show as a <textarea> field that is partly formatted as a "success" button

**Expected behavior:** 
As in previous versions of bootstrap 3, the source text should be shown as a grayed out field with all the text shown including newspaces between paragraphs.
(See screenshot 2)

**Actual behavior:** [What actually happened]
The complete source text is shown on one line, and the field looks like a green success button when one hovers over it with the mouse pointer.
(See screenshot 1)

### Versions

* [Bootstrap3 Template] - Template v2024-02-06 (stable/20240206)
* [DokuWiki] - Release 2024-02-06a "Kaos"
* [Plugins] - irrelevant
* [PHP] - 8.2
* [Browser] - Mozilla Firefox, Chrome, Edge, etc.

### Screenshots or Logs

Screenshot showing issue **before** fix.

![image](https://github.com/user-attachments/assets/5549b123-4bf6-41f2-83b4-2a420548b6e5)

Screenshot **after** fix.

![image](https://github.com/user-attachments/assets/36a25b4d-b8ed-44c2-9e1c-436102e6c432)

### Suggested fix

File is ./lib/tpl/bootstrap3/EventHandlers.php

**ORIGINAL**

```php
public function formEditOutput(\Doku_Event $event)
...
$form->getElementAt($form->findPositionByAttribute('name', 'do[save]'))
    ->addClass('btn btn-success mr-2')->attr('data-dw-icon', 'mdi:content-save');

$form->getElementAt($form->findPositionByAttribute('name', 'do[preview]'))
    ->addClass('btn btn-default mr-2')->attr('data-dw-icon', 'mdi:file-document-outline');

$form->getElementAt($form->findPositionByAttribute('name', 'do[cancel]'))
    ->addClass('btn btn-default mr-2')->attr('data-dw-icon', 'mdi:arrow-left');
...

``` 

**FIX**

```php
public function formEditOutput(\Doku_Event $event)
...
if ($form->findPositionByAttribute('name', 'do[save]') != false)
  $form->getElementAt($form->findPositionByAttribute('name', 'do[save]'))
    ->addClass('btn btn-success mr-2')->attr('data-dw-icon', 'mdi:content-save');

if ($form->findPositionByAttribute('name', 'do[preview]') != false)
  $form->getElementAt($form->findPositionByAttribute('name', 'do[preview]'))
    ->addClass('btn btn-default mr-2')->attr('data-dw-icon', 'mdi:file-document-outline');

if ($form->findPositionByAttribute('name', 'do[cancel]') != false)
  $form->getElementAt($form->findPositionByAttribute('name', 'do[cancel]'))
    ->addClass('btn btn-default mr-2')->attr('data-dw-icon', 'mdi:arrow-left');
...

```

**Comment by giterlizzi** [comment]
FIXED in master branch.
Thank you for the patch suggestion!
