### ISSUE TITLE
Wrong CSS selector in css/template.less

### ISSUE THREAD

**Issue by gianfrus** [giterlizzi/dokuwiki-template-bootstrap3#612]
### Wrong CSS selector (bug found in code)

I think that, in file 'css/template.less', the CSS selector in line 78:

`h1, h2, h3, h4 h5 {`
`    margin: 10px 0 5px 0;`
`  }`

should be

`h1, h2, h3, h4, h5 {`
`    margin: 10px 0 5px 0;`
`  }`

**This bugfix might solve some other related issues.**

### Versions

* [Bootstrap3 Template] 2024-02-06
* [DokuWiki] 2024-02-06b "Kaos"

**Comment by giterlizzi** [comment]
FIXED in master branch
